### ISSUE TITLE
部分模型加载完后空白，h5移动端当中模型超出可视窗口

### ISSUE THREAD

**Issue by huxiao0802** [king2088/vue-3d-loader#1]
我使用vue2，安装了vue-3d-loader@1.2.4版本，部分模型加载不出来，并且有的模型超出可视窗口，动画也只有一小部分可以加载出来

**Comment by king2088** [comment]
1. 模型无法加载，请确保模型格式为.dae/.fbx/.gltf/.glb/.obj/.ply/.stl/.json
2. 如果是多个模型一起加载，很可能会影响到动画效果，比如fbx与gltf一起加载，fbx本身有动画，但是两种模型一起几种后，fbx很可能会丢失动画。
3. 模型超出可视窗口，可以通过设置cameraPosition以及scale的方式来调整模型角度以及缩放。

最后，感谢你的支持。

**Comment by huxiao0802** [comment]
> 1. 模型无法加载，请确保模型格式为.dae/.fbx/.gltf/.glb/.obj/.ply/.stl/.json
> 2. 如果是多个模型一起加载，很可能会影响到动画效果，比如fbx与gltf一起加载，fbx本身有动画，但是两种模型一起几种后，fbx很可能会丢失动画。
> 3. 模型超出可视窗口，可以通过设置cameraPosition以及scale的方式来调整模型角度以及缩放。
> 
> 最后，感谢你的支持。

模型超出可视窗口，我先前使用了[Vue 3D Model]同样遇到了这个问题，尝试过设置scale后模型缩小了，但是都位于底部并非居中，随后我又尝试cameraPosition相机位置的x轴去进行缩小模型，由于模型是后台接口返回的文件地址，可能有不同的模型用一套代码展示，结果较大的模型缩放完正好，较小的模型调整了相机x轴后缩小的看不见了，请教下有什么办法可以让模型缩放后居中或者改变相机x轴距离是动态的已确保不同大小的模型都可以正常显示

**Comment by king2088** [comment]
> > 1. 模型无法加载，请确保模型格式为.dae/.fbx/.gltf/.glb/.obj/.ply/.stl/.json
> > 2. 如果是多个模型一起加载，很可能会影响到动画效果，比如fbx与gltf一起加载，fbx本身有动画，但是两种模型一起几种后，fbx很可能会丢失动画。
> > 3. 模型超出可视窗口，可以通过设置cameraPosition以及scale的方式来调整模型角度以及缩放。
> > 
> > 最后，感谢你的支持。
> 
> 模型超出可视窗口，我先前使用了[Vue 3D Model]同样遇到了这个问题，尝试过设置scale后模型缩小了，但是都位于底部并非居中，随后我又尝试cameraPosition相机位置的x轴去进行缩小模型，由于模型是后台接口返回的文件地址，可能有不同的模型用一套代码展示，结果较大的模型缩放完正好，较小的模型调整了相机x轴后缩小的看不见了，请教下有什么办法可以让模型缩放后居中或者改变相机x轴距离是动态的已确保不同大小的模型都可以正常显示

就目前来说，暂时不支持对多模型加载后，对其中模型进行位置、缩放的修改，当前所有模型默认的位置都是x:0,y:0,z:0的坐标。不过下一版本可能会增加这项需求到当前插件。
另外，你的这个原因主要是由于模型的比例不一致导致的，如果所有模型都通过一个3D建模软件进行位置的更改后，再重新导出，将会解决这个问题。

**Comment by king2088** [comment]
目前发布的1.2.5版本已经支持单独为多个3D模型设置position/rotation/scale，请查看文档https://github.com/king2088/vue-3d-loader/tree/1.2.x，演示代码：https://github.com/king2088/vue-3d-loader/blob/1.2.x/src/examples/load-multiple-models.vue
