### ISSUE TITLE
请问如何加载gltf动画模型

### ISSUE THREAD

**Issue by ruanqingpeng** [king2088/vue-3d-loader#10]
当把disable-anmation案例中的 dae小人动画模型 换成glb动画模型之后 加载不出该模型的动画。请问具体原因是什么呢

**Comment by king2088** [comment]
加载的是单个3D模型还是多个3D模型？如果是多个模型，目前应该会出现无法播放动画的情况。如果是单个模型，请将模型发给我看一下，可以发送到514337551#qq.com(将#改成@)

**Comment by king2088** [comment]
长时间未回复，关闭此issue
