### ISSUE TITLE
最新版的功能也是兼容Vue2吗

### ISSUE THREAD

**Issue by 110sec** [king2088/vue-3d-loader#100]

**Comment by king2088** [comment]
最新版2.2.x并不支持vue2，不过我每次的更新都会同步更新vue2版本的，如果需要使用vue2版本，直接安装最新版的1.3.x版本即可

**Comment by 110sec** [comment]
今天试了vue2版，请问下，怎么将模型的位置设置在屏幕正中间并保持一定比例哈，组件设置高度属性存在报错问题

**Comment by king2088** [comment]
> 今天试了vue2版，请问下，怎么将模型的位置设置在屏幕正中间并保持一定比例哈，组件设置高度属性存在报错问题

报错的问题请把代码，错误信息发出来

**Comment by king2088** [comment]
想要模型居中可以打开[网格及坐标线](https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/enable-axes-grid.html)，调整摄像机位置（[cameraPosition](https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#cameraposition)）以及模型位置（[position](https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#position)）进行设置
