### ISSUE TITLE
setCrossOrigin的问题

### ISSUE THREAD

**Issue by lfk0719** [king2088/vue-3d-loader#104]
我在上传glb等3d资源时想进行展示   url.value = URL.createObjectURL(event.raw); 获取到二进制文件然后转url加载报错

**Comment by king2088** [comment]
如果通过blob的URL转换无法加载模型且报错，应该是由于目前插件并不支持返回纯二进制接口的数据，建议采用可下载链接

**Comment by shi0202** [comment]
那以后组件会支持加载纯二进制进口数据使用URL.createObjectURL生成的地址吗大佬

**Comment by king2088** [comment]
> 那以后组件会支持加载纯二进制进口数据使用URL.createObjectURL生成的地址吗大佬

后续有空的话，我会考虑将加载二进制加入到内
