### ISSUE TITLE
对了，大佬，就是我通过ref查看内部方法属性这些，为什么打印出来是undefined啊，比如我想看看场景里面的信息，但是undefined,不知道为什么

### ISSUE THREAD

**Issue by FengIsTao** [king2088/vue-3d-loader#106]
![image](https://github.com/king2088/vue-3d-loader/assets/50825076/dbff8656-7c98-4b3b-a4a9-c4185eaf46c5)

**Comment by FengIsTao** [comment]
可以通过ref获取里面的scene,camera这些嘛？

**Comment by king2088** [comment]
通过ref可能无法获取到其中的内容，不建议这样使用，如果要得到场景中的数据，可以通过load事件获取

**Comment by FengIsTao** [comment]
嗯嗯，谢谢作者大大，我试试
