### ISSUE TITLE
 加载的模型全黑是为什么呢？

### ISSUE THREAD

**Issue by xuyhtuuio** [king2088/vue-3d-loader#109]

**Comment by king2088** [comment]
可以尝试一下outputEncoding属性 https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#outputencoding

**Comment by xuyhtuuio** [comment]
加上了还是不行呢，它主要报几个跨域的错，是什么问题呢？

**Comment by king2088** [comment]
> 加上了还是不行呢，它主要报几个跨域的错，是什么问题呢？

如果上跨服的问题可能比较难以处理，目前暂时无太好的解决方法

**Comment by xuyhtuuio** [comment]
就是有很多图片加载不出来，报404

**Comment by king2088** [comment]
> 就是有很多图片加载不出来，报404

如果是图片问题，要看一下图片所在目录或路径位置是否正确，如果路径不正确肯定出现404

**Comment by xuyhtuuio** [comment]
额我换了一个格式就好了，用的.gltf格式就行了
