### ISSUE TITLE
移动鼠标，改变模型视角

### ISSUE THREAD

**Issue by leeycode** [king2088/vue-3d-loader#11]
大佬好，请问有有没有可能做成类似腾讯云首页的banner图一样，鼠标移动，模型的视角也改变呢？
[https://cloud.tencent.com/](示例)

**Comment by king2088** [comment]
> 大佬好，请问有有没有可能做成类似腾讯云首页的banner图一样，鼠标移动，模型的视角也改变呢？ [https://cloud.tencent.com/](%E7%A4%BA%E4%BE%8B)

由于vue-3d-loader仅是为了加载渲染3D模型而开发的，并不具备此功能。
你可以尝试使用threeJS进行制作，大概理论如下：
1、threeJS获取模型数据
2、设置模型的rotation跟随鼠标在屏幕的位置而旋转模型角度

**Comment by leeycode** [comment]
感谢解答！
