### ISSUE TITLE
pointLightFollowCamera in Version "next"   (for Vue3) 

### ISSUE THREAD

**Issue by lalula** [king2088/vue-3d-loader#111]
I noticed that the feature pointLightFollowCamera is missing in Version "next"
Are there any plans to reimplement it?

**Comment by king2088** [comment]
thx, but you can use "master", LightFollowCamera in the "master", the "next" unsynchronized "master" branch.

**Comment by king2088** [comment]
> I noticed that the feature pointLightFollowCamera is missing in Version "next" Are there any plans to reimplement it?

Thx, but you can use "master", LightFollowCamera in the "master", the "next" unsynchronized "master" branch.
