### ISSUE TITLE
process进度为100%与网页渲染模型完成并不完全同步

### ISSUE THREAD

**Issue by MOr1s2** [king2088/vue-3d-loader#115]
加载.obj格式的文件时，(event.loaded / event.total)*100为100%时，网页依旧需要一两秒钟才能渲染完成模型，请问这是正常现象吗？

**Comment by king2088** [comment]
> 加载.obj格式的文件时，(event.loaded / event.total)*100为100%时，网页依旧需要一两秒钟才能渲染完成模型，请问这是正常现象吗？

在使用process的时候，如果是在本地开发环境下使用，则无法正常计算出加载的情况。必须打包后放到nginx或其他http服务器内，才能得到正常的process进度。原因主要是因为webpack本地启动的http服务没有提供必要的response headers关于文件的Content-Length导致本地无法感知到正确的process

**Comment by MOr1s2** [comment]
我明白了，感谢答复:)
