### ISSUE TITLE
ply点云无法正确加载

### ISSUE THREAD

**Issue by XiGuang** [king2088/vue-3d-loader#118]
在vue3中，我使用以下代码尝试可视化点云，但是却出现了胡乱的mesh
```
<script setup lang="ts">
import { vue3dLoader } from "vue-3d-loader";
</script>

<template>
  <div>
    <vue3dLoader
        filePath="/point_cloud.ply"
        :backgroundAlpha="0.2"
        :height="600"
    />
  </div>
</template>
```

![image](https://github.com/king2088/vue-3d-loader/assets/16274121/aa1d68d1-b7ce-4dd7-9a7c-a353b8b09b54)

实际的点云如下图所示：
![image](https://github.com/king2088/vue-3d-loader/assets/16274121/08be2194-7ee4-47f9-b6ef-2df8a0113428)

**Comment by king2088** [comment]
> 在vue3中，我使用以下代码尝试可视化点云，但是却出现了胡乱的mesh
> 
> ```
> <script setup lang="ts">
> import { vue3dLoader } from "vue-3d-loader";
> </script>
> 
> <template>
>   <div>
>     <vue3dLoader
>         filePath="/point_cloud.ply"
>         :backgroundAlpha="0.2"
>         :height="600"
>     />
>   </div>
> </template>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16274121/325248014-aa1d68d1-b7ce-4dd7-9a7c-a353b8b09b54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDY5NDMsIm5iZiI6MTcxNDMwNjY0MywicGF0aCI6Ii8xNjI3NDEyMS8zMjUyNDgwMTQtYWExZDY4ZDEtYjdjZS00ZGQ3LTlhN2MtYTM1M2I4YjA5YjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEyMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYzI1NTlkYmRiOThiYjFhMzE2NGE1MzQyNmY5ODVhNTUxYWFiODVkZDZlZmUyY2FlODA1YzUxNTBhOWE1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LekBsKrXadz3cUoe2lPK6HNuFRU4r3MoGy2u4Hd1AQ4)
> 
> 实际的点云如下图所示： ![image](https://private-user-images.githubusercontent.com/16274121/325248454-08be2194-7ee4-47f9-b6ef-2df8a0113428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDY5NDMsIm5iZiI6MTcxNDMwNjY0MywicGF0aCI6Ii8xNjI3NDEyMS8zMjUyNDg0NTQtMDhiZTIxOTQtN2VlNC00N2Y5LWI2ZWYtMmRmOGEwMTEzNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEyMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZDhhNmEzZGExODRhZjM5NDFjZjM3ODJlOTAxMzBiN2IwYzg0NzA3MDI3ZTA2MDkwNTYzYmJjMzI4YTU1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NT3nF3MoBgfYZVHyEcQX2H36o4WO8Sh5sBLKhb_653s)

建议将stl转换为gltf格式使用

**Comment by XiGuang** [comment]
谢谢，已经解决了~
