### ISSUE TITLE
模型自动播放

### ISSUE THREAD

**Issue by caozhenzhu** [king2088/vue-3d-loader#12]
你好，现在两个模型一个有动画一个没有，autoPlay就没有用了，如果只有一个有动画的模型就可以用，这个是什么问题呢

**Comment by king2088** [comment]
> 你好，现在两个模型一个有动画一个没有，autoPlay就没有用了，如果只有一个有动画的模型就可以用，这个是什么问题呢

这是一个bug，等待找到解决方法，再给你回复

**Comment by caozhenzhu** [comment]
好的

**Comment by quanliheng** [comment]
你好，请问这个bug解决了吗，我也遇到了同样的问题

**Comment by king2088** [comment]
目前此bug将在2.1.1及1.3.0版本中修复
