### ISSUE TITLE
线上环境操作模型时一直会报错，^1.3.7

### ISSUE THREAD

**Issue by binGe21** [king2088/vue-3d-loader#120]
![image](https://github.com/king2088/vue-3d-loader/assets/135292570/6ed48312-76c3-472e-adf8-df222c51447f)

**Comment by king2088** [comment]
1.3.7支持的是Vue2，请确保使用的是Vue2版本。

**Comment by binGe21** [comment]
> 1.3.7支持的是Vue2，请确保使用的是Vue2版本。

对的，使用的Vue2
