### ISSUE TITLE
vue2 版本@mousemove="onMouseMove" 事件不起作用

### ISSUE THREAD

**Issue by Jetter-li** [king2088/vue-3d-loader#121]
onMouseMove(event, intersected) {
      debugger
      if (this.object) {
        this.object.material.color.setStyle("#fff");
      }
      if (intersected) {
        this.object = intersected.object;
        this.object.material.color.setStyle("#13ce66");
      }
    },
参考这个例子，intersected一直为空，怎么解决这个问题呢？

**Comment by king2088** [comment]
你的问题可能和这个issue一样https://github.com/king2088/vue-3d-loader/issues/39

**Comment by Jetter-li** [comment]
好的，谢谢，加上 :intersectRecursive="true" 参数可以用了
