### ISSUE TITLE
点击模型材料选中问题

### ISSUE THREAD

**Issue by Jetter-li** [king2088/vue-3d-loader#122]
您好，我在点击模型上的机柜材料设置选中颜色时遇到了个问题，设置完后模型上所有机柜材料都变了颜色，而不是只给点击的机柜材料设置颜色，您看看是哪里的问题呢？this.selectObject.material 不是获取的当前点击的机柜材料吗？
相关代码：
onMousedown(event, intersected) {
      // debugger
      if (this.selectObject) {
        console.log(this.selectObject)
        this.selectObject.material.color.setStyle("#fff");
      }
      if (intersected) {
        this.selectObject = intersected.object;
        console.log(this.selectObject)
        this.selectObject.material.color.setStyle("#13ce66");
      }
    },

截图：
点击前：
![01](https://github.com/king2088/vue-3d-loader/assets/53339112/dd464f36-af7e-49dc-864e-23638e70d0a4)

点击后：
![02](https://github.com/king2088/vue-3d-loader/assets/53339112/df4772c1-92c8-4d52-abd1-1533c24cd974)

**Comment by king2088** [comment]
这是模型的问题，模型没有分组信息或者ID，无法对单独的做颜色管理，想要对单独的做管理，得有对应的分组或单独的子类

**Comment by Jetter-li** [comment]
好的，谢谢
