### ISSUE TITLE
How to get final position&rotation&scale

### ISSUE THREAD

**Issue by August-Zong** [king2088/vue-3d-loader#125]
Hi. author. we can set init value position&rotation&scale by pass attribute to it, but when position&rotation&scale behavior by mouse, can we get final data by any API?  ths

**Comment by king2088** [comment]
> Hi. author. we can set init value position&rotation&scale by pass attribute to it, but when position&rotation&scale behavior by mouse, can we get final data by any API? ths

No such API available now.
