### ISSUE TITLE
fbx在动画的某些模型在苹果手机浏览器打开会重复刷新页面

### ISSUE THREAD

**Issue by tlxiaociwei** [king2088/vue-3d-loader#128]
例如 https://cksj-bucket.oss-cn-shenzhen.aliyuncs.com/freespot.FBX202404114bcf23be-933b-4739-9e64-e5bb3c4d5d05.FBX 这个模型
也没有触发加载失败的方法

**Comment by king2088** [comment]
目前暂未在移动端测试和使用，移动端可能会有问题。
