### ISSUE TITLE
事件没有第二个参数

### ISSUE THREAD

**Issue by tudan110** [king2088/vue-3d-loader#13]
在 vue2 中使用 1.2.9 版本，click 事件只有第一个参数 event，第二个参数为 null

**Comment by king2088** [comment]
> 在 vue2 中使用 1.2.9 版本，click 事件只有第一个参数 event，第二个参数为 null

这是由于默认清空下不会自动监测后代对象的交点导致的，因此，可以尝试开启监测后代交点，API中提到`intersectRecursive`参数，将其设置为true即可

|prop | type | default | description
|-- | -- | -- | -- |
|intersectRecursive | boolean | false | If true, it also checks all descendants. Otherwise it only checks intersection with the object.|

**Comment by tudan110** [comment]
> 

听我说，谢谢你，因为有你，温暖了四季

**Comment by JaneYork** [comment]
> intersectRecursive

@king2088 @tudan110   一个模型，比如有四个门把手，怎么定位点击了哪个把手呢？ 坐标用啥拿到？
