### ISSUE TITLE
labels 标注模块

### ISSUE THREAD

**Issue by GBinll** [king2088/vue-3d-loader#135]
vue2的项目中：
labels 使用动态添加是不是无法直接显示在模型上的？ handleClick(event, intersected){
 if (intersected.object.type == "Mesh"){
    this.labels.push( let labes = {
                image: image1,//自定义图标
                // position: { x: -35, y: 40, z: -140 },
                position: { x: intersected.point.x, y: intersected.point.y, z: intersected.point.z },
                scale: { x: 20, y: 20, z: 20 },
                sid: 2,
              };)
    }
}
直接这样是不是无法先添加的标注无法显示在模型上

**Comment by king2088** [comment]
> vue2的项目中： labels 使用动态添加是不是无法直接显示在模型上的？ handleClick(event, intersected){ if (intersected.object.type == "Mesh"){ this.labels.push( let labes = { image: image1,//自定义图标 // position: { x: -35, y: 40, z: -140 }, position: { x: intersected.point.x, y: intersected.point.y, z: intersected.point.z }, scale: { x: 20, y: 20, z: 20 }, sid: 2, };) } } 直接这样是不是无法先添加的标注无法显示在模型上

不能使用这种动态方式，你可以动态修改this.labels中的属性值即可，无需通过event进行设置
