### ISSUE TITLE
使用默认宽高，只有宽度，没有高度

### ISSUE THREAD

**Issue by Z-xiaoxuan** [king2088/vue-3d-loader#138]
<img width="435" alt="image" src="https://github.com/user-attachments/assets/c92dc6ba-45d6-42f4-9e16-12f3e008864a">

**Comment by king2088** [comment]
> <img alt="image" width="435" src="https://private-user-images.githubusercontent.com/89857706/391870502-c92dc6ba-45d6-42f4-9e16-12f3e008864a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDQ4MDQsIm5iZiI6MTczNDk0NDUwNCwicGF0aCI6Ii84OTg1NzcwNi8zOTE4NzA1MDItYzkyZGM2YmEtNDVkNi00MmY0LTllMTYtMTJmM2UwMDg4NjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA5MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODRmZDYzMGEyOWU0ZGUxNTNjMTZhZDgwOThlN2QxMTUxZGZiODgyODcxOWVmMDVlMzY0NzY3NWY3NzY0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gw50Wnpm7Z8GhycB8nNXuG7VOVw3rWEvXZ-_GPSDYqs">

正常情况下，会根据父层获取高度，如果父层未设置高度，则vue-3d-loader高度也不会被设置，建议将父层高度设置为100%或者固定高度！

**Comment by king2088** [comment]
> <img alt="image" width="435" src="https://private-user-images.githubusercontent.com/89857706/391870502-c92dc6ba-45d6-42f4-9e16-12f3e008864a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDQ4MDQsIm5iZiI6MTczNDk0NDUwNCwicGF0aCI6Ii84OTg1NzcwNi8zOTE4NzA1MDItYzkyZGM2YmEtNDVkNi00MmY0LTllMTYtMTJmM2UwMDg4NjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA5MDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmODRmZDYzMGEyOWU0ZGUxNTNjMTZhZDgwOThlN2QxMTUxZGZiODgyODcxOWVmMDVlMzY0NzY3NWY3NzY0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Gw50Wnpm7Z8GhycB8nNXuG7VOVw3rWEvXZ-_GPSDYqs">

正常情况下，会根据父层获取高度，如果父层未设置高度，则vue-3d-loader高度也不会被设置，建议将父层高度设置为100%或者固定高度！
