### ISSUE TITLE
vue2.x 为什么.glb格式添加 rotation scale就会不显示模型啊

### ISSUE THREAD

**Issue by QingchengWait** [king2088/vue-3d-loader#16]
vue2.x 为什么.glb格式添加 rotation scale就会不显示模型啊,
    <vue3dLoader
      :width="width"
      :height="height"
      :lights="lights"
      outputEncoding="sRGB"
      :showFps="true"
      :rotation="rotation"
      :scale="[{x:1, y:2, z:1}]
      filePath="static/models/jiangpai1.glb"
    >
    </vue3dLoader>

**Comment by QingchengWait** [comment]
我想使模型旋转,但是发现按照实例上的方法不行,添加旋转属性的话,就不会显示模型

**Comment by king2088** [comment]
> vue2.x 为什么.glb格式添加 rotation scale就会不显示模型啊, <vue3dLoader :width="width" :height="height" :lights="lights" outputEncoding="sRGB" :showFps="true" :rotation="rotation" :scale="[{x:1, y:2, z:1}] filePath="static/models/jiangpai1.glb" >

请将模型发我邮箱，我进行测试，514337551#qq.com（将#改为@）

**Comment by king2088** [comment]
长时间未提供新的信息，关闭此issue

**Comment by king2088** [comment]
长时间未提供新的信息，关闭此issue
