### ISSUE TITLE
import引入报错

### ISSUE THREAD

**Issue by 0616zxy** [king2088/vue-3d-loader#17]
./node_modules/vue-3d-loader/dist/vue-3d-loader.umd.min.js
Module parse failed: Unexpected token (7:767931)
You may need an appropriate loader to handle this file type.

**Comment by king2088** [comment]
> ./node_modules/vue-3d-loader/dist/vue-3d-loader.umd.min.js Module parse failed: Unexpected token (7:767931) You may need an appropriate loader to handle this file type.

Please provide more information, such as: Vue version and vue-3d-loader version and page code

**Comment by king2088** [comment]
长时间未提供更多信息，关闭此issue
