### ISSUE TITLE
glb模型autoPlay属性失效

### ISSUE THREAD

**Issue by exile-yy** [king2088/vue-3d-loader#18]
我下载之后载入glb模型添加autoPlay属性模型还是没有开启动画

**Comment by exile-yy** [comment]
依赖包
{
  "name": "vue-project",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 4173"
  },
  "dependencies": {
    "dat.gui": "^0.7.9",
    "gsap": "^3.11.3",
    "pinia": "^2.0.17",
    "three": "^0.143.0",
    "vue": "^3.2.37",
    "vue-3d-loader": "^2.1.0",
    "vue-router": "^4.1.3"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.1",
    "vite": "^3.0.4"
  }
}
页面代码
<template>
  <div class="">
  </div>
  <vue3dLoader
  filePath="/3dmodule/gltf/xq01.glb"
  :cameraPosition="{ x: 10, y: 700, z: 1000 }"
  :enableDraco="true"
  outputEncoding="sRGB"
  :height="900"
  :autoPlay="true"
/>
</template>

<script setup>
import {} from 'vue'
</script>

<style scoped>
*{
  padding: 0;
  margin: 0;
}
.draco-demo {
  position: absolute;
  top: 10px;
  left: 50%;
  transform: translateX(-50%);
  z-index: 10;
  color: red;
  width: 480px;
  background-color: #f2f2f2;
  padding: 5px 10px;
  line-height: 2;
}
.draco-demo a {
  color: #fff;
  background-color: blue;
  padding: 2px 8px;
  border-radius: 4px;
  margin: 0 5px;
}
.draco-demo a:hover {
  color: #fff;
  background-color: rgb(17, 235, 126);
}
</style>

**Comment by exile-yy** [comment]
依赖包
{
  "name": "vue-project",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 4173"
  },
  "dependencies": {
    "dat.gui": "^0.7.9",
    "gsap": "^3.11.3",
    "pinia": "^2.0.17",
    "three": "^0.143.0",
    "vue": "^3.2.37",
    "vue-3d-loader": "^2.1.0",
    "vue-router": "^4.1.3"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.1",
    "vite": "^3.0.4"
  }
}
页面代码
<template>
  <div class="">
  </div>
  <vue3dLoader
  filePath="/3dmodule/gltf/xq01.glb"
  :cameraPosition="{ x: 10, y: 700, z: 1000 }"
  :enableDraco="true"
  outputEncoding="sRGB"
  :height="900"
  :autoPlay="true"
/>
</template>

**Comment by exile-yy** [comment]
页面代码
<template>
  <div class="">
  </div>
  <vue3dLoader
  filePath="/3dmodule/gltf/xq01.glb"
  :cameraPosition="{ x: 10, y: 700, z: 1000 }"
  :enableDraco="true"
  outputEncoding="sRGB"
  :height="900"
  :autoPlay="true"
/>
</template>

**Comment by king2088** [comment]
> 我下载之后载入glb模型添加autoPlay属性模型还是没有开启动画

请确保glb文件确实拥有动画属性

**Comment by king2088** [comment]
> 依赖包 { "name": "vue-project", "version": "0.0.0", "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview --port 4173" }, "dependencies": { "dat.gui": "^0.7.9", "gsap": "^3.11.3", "pinia": "^2.0.17", "three": "^0.143.0", "vue": "^3.2.37", "vue-3d-loader": "^2.1.0", "vue-router": "^4.1.3" }, "devDependencies": { "@vitejs/plugin-vue": "^3.0.1", "vite": "^3.0.4" } } 页面代码

确保安装的vue-3d-loader是当前最新2.1.2版本，另外经过我的测试，glb文件在2.1.2版本中autoPlay并无问题

**Comment by exile-yy** [comment]
> > 依赖包 { "name": "vue-project", "version": "0.0.0", "scripts": { "dev": "vite", "build": "vite build", "preview": "vite preview --port 4173" }, "dependencies": { "dat.gui": "^0.7.9", "gsap": "^3.11.3", "pinia": "^2.0.17", "three": "^0.143.0", "vue": "^3.2.37", "vue-3d-loader": "^2.1.0", "vue-router": "^4.1.3" }, "devDependencies": { "@vitejs/plugin-vue": "^3.0.1", "vite": "^3.0.4" } } 页面代码
> 
> 确保安装的vue-3d-loader是当前最新2.1.2版本，另外经过我的测试，glb文件在2.1.2版本中autoPlay并无问题

谢谢 确实是版本问题
