### ISSUE TITLE
怎么主动销毁此组件

### ISSUE THREAD

**Issue by hexinjun888** [king2088/vue-3d-loader#19]
用vue的v-if动态销毁，发现浏览器占用的内存太高了，卡死了

**Comment by king2088** [comment]
> 用vue的v-if动态销毁，发现浏览器占用的内存太高了，卡死了

你使用的是什么版本？做的是什么操作，导致内存过高？

**Comment by hexinjun888** [comment]
![image](https://user-images.githubusercontent.com/36840894/197961535-d9a17174-125d-4c16-9f7c-64820561b393.png)
版本：1.0.0
我想在页面更新时，动态调整3D的显示

**Comment by king2088** [comment]
请将版本升级到1.2.11尝试是否还有此问题，如果存在，请回复，后续版本中再修复此问题

**Comment by hexinjun888** [comment]
版本已经升级，还是占用太高，没有办法使用，建议增加主动销毁方法。本身three已经很占用内存了，不销毁占用的更高。

**Comment by king2088** [comment]
> 版本已经升级，还是占用太高，没有办法使用，建议增加主动销毁方法。本身three已经很占用内存了，不销毁占用的更高。

你的模型有多少个？是什么类型的模型文件？模型文件有多大？

**Comment by hexinjun888** [comment]
就一个模型，gltf格式，但是界面上我要动态的改变此模型的长和宽，还有加载的模型。
![image](https://user-images.githubusercontent.com/36840894/197968435-ae094df0-8936-4537-9de3-91308c2bd949.png)

**Comment by king2088** [comment]
> 就一个模型，gltf格式，但是界面上我要动态的改变此模型的长和宽，还有加载的模型。
> ![image](https://user-images.githubusercontent.com/36840894/197968435-ae094df0-8936-4537-9de3-91308c2bd949.png)
> 

你可以自行尝试对源码进行修改以达到需求，或者等待之后的版本修复此问题

**Comment by hexinjun888** [comment]
大概什么时候修复

**Comment by king2088** [comment]
> 大概什么时候修复

暂无明确计划

**Comment by king2088** [comment]
> > 大概什么时候修复
> 
> 暂无明确计划

请关注版本变更

**Comment by hexinjun888** [comment]
算了，我自己来
