### ISSUE TITLE
请问你们是怎么引入进项目的，我为什么一直报错呢，初学者，请见谅。

### ISSUE THREAD

**Issue by qihao0629** [king2088/vue-3d-loader#2]
我按照文档，引入进项目，用的vue2，然后一直报错，实在是没弄明白，哪位大神知道原因，感谢了。
错误：Vue warn]: Error in mounted hook: "TypeError: this.onResize is not a function"

**Comment by king2088** [comment]
vue2需要安装1.x.x版本，请确保你安装的是1.x.x版本

**Comment by qihao0629** [comment]
您好，我安装的就是1.2.5版本的。所以特别的奇怪

**Comment by qihao0629** [comment]
> vue2需要安装1.x.x版本，请确保你安装的是1.x.x版本

您好，我安装的是1.2.5版本的，所以我也很困惑

**Comment by king2088** [comment]
安装的时候使用npm install vue-3d-loader@1.2.5
```vue
<template>
  <vue3dLoader
    filePath="/models/collada/stormtrooper/stormtrooper.dae"
    :scale="{ x: 0.2, y: 0.2, z: 0.2 }"
  />
</template>
<script>
import {vue3dLoader} from 'vue-3d-loader'
export default {
components: {vue3dLoader}
};
</script>
```

**Comment by qihao0629** [comment]
> 安装的时候使用npm install vue-3d-loader@1.2.5
> 
> ```
> <template>
>   <vue3dLoader
>     filePath="/models/collada/stormtrooper/stormtrooper.dae"
>     :scale="{ x: 0.2, y: 0.2, z: 0.2 }"
>   />
> </template>
> <script>
> import {vue3dLoader} from 'vue-3d-loader'
> export default {
> components: {vue3dLoader}
> };
> </script>
> ```

大神，我也是这么引入的，但是一执行到这，就报错误：Vue warn]: Error in mounted hook: "TypeError: this.onResize is not a function"，

**Comment by king2088** [comment]
> > 安装的时候使用npm install vue-3d-loader@1.2.5
> > ```
> > <template>
> >   <vue3dLoader
> >     filePath="/models/collada/stormtrooper/stormtrooper.dae"
> >     :scale="{ x: 0.2, y: 0.2, z: 0.2 }"
> >   />
> > </template>
> > <script>
> > import {vue3dLoader} from 'vue-3d-loader'
> > export default {
> > components: {vue3dLoader}
> > };
> > </script>
> > ```
> 
> 大神，我也是这么引入的，但是一执行到这，就报错误：Vue warn]: Error in mounted hook: "TypeError: this.onResize is not a function"，

你能不能把你的代码贴上来啊，你这样我也不知道你啥情况啊，把你主要的代码以及package.json内的配置都贴上来吧

**Comment by king2088** [comment]
TypeError: this.onResize is not a function，你能不能检查下自己代码里是不是有个 this.onResize方法，这个方法没有定义啊

**Comment by qihao0629** [comment]
> TypeError: this.onResize is not a function，你能不能检查下自己代码里是不是有个 this.onResize方法，这个方法没有定义啊

这是我的package.json里的代码
{
  "dependencies": {
    "html2canvas": "^1.0.0-rc.4",
    "qrcodejs2": "0.0.2",
    "uview-ui": "^2.0.28",
    "vue-3d-loader": "^1.2.5",
    "vue-aliplayer": "^1.0.0"
  }
}

**Comment by qihao0629** [comment]
> TypeError: this.onResize is not a function，你能不能检查下自己代码里是不是有个 this.onResize方法，这个方法没有定义啊

我项目里没有这句话，我看是插件里面有这个方法调用，插件报错

**Comment by king2088** [comment]
能不能把你的代码放出来啊，能不能一次性将代码，package.json内的所有都贴出来啊，不然我无法帮助你！我试过vue2，没有你这样的问题

**Comment by qihao0629** [comment]
> 能不能把你的代码放出来啊，能不能一次性将代码，package.json内的所有都贴出来啊，不然我无法帮助你！我试过vue2，没有你这样的问题

我的主项目package.json里，就只有这几行代码，然后调用的地方的代码是这样的。就没有其他的了。然后就报错
<template>
		  <vue3dLoader
		      filePath="/a71b9267cb26f7acd73c19ef71a7f523.glb"
		      :scale="{ x: 0.2, y: 0.2, z: 0.2 }"
		    />
</template>

<script>
import {vue3dLoader} from 'vue-3d-loader'
export default {
components: {vue3dLoader}
};
</script>

**Comment by king2088** [comment]
这是vue插件，你的package.json中没有看到vue啊

**Comment by qihao0629** [comment]
> 这是vue插件，你的package.json中没有看到vue啊

我是用HBuilder 来编译的项目，建的是uni-app项目，用的是vue2语言

**Comment by qihao0629** [comment]
我这写了个demo，，也加载不上去，就是很奇怪。。我分享个链接，压缩包太大，传不上来，不好意思。
链接: https://pan.baidu.com/s/1bc4PSBGiwxsVT5psb2q0Yg?pwd=8h7i 提取码: 8h7i 
--来自百度网盘超级会员v6的分享

**Comment by king2088** [comment]
> 我这写了个demo，，也加载不上去，就是很奇怪。。我分享个链接，压缩包太大，传不上来，不好意思。 链接: https://pan.baidu.com/s/1bc4PSBGiwxsVT5psb2q0Yg?pwd=8h7i 提取码: 8h7i --来自百度网盘超级会员v6的分享

经过尝试，无法与uni-app兼容，估计需要单独为uni-app开发一个插件，本插件不支持uni-app，谢谢

**Comment by qihao0629** [comment]
> > 我这写了个demo，，也加载不上去，就是很奇怪。。我分享个链接，压缩包太大，传不上来，不好意思。 链接: https://pan.baidu.com/s/1bc4PSBGiwxsVT5psb2q0Yg?pwd=8h7i 提取码: 8h7i --来自百度网盘超级会员v6的分享
> 
> 经过尝试，无法与uni-app兼容，估计需要单独为uni-app开发一个插件，本插件不支持uni-app，谢谢

好的，感谢百忙之中，帮我解决问题，期待未来有兼容的插件问世，谢谢😊
