### ISSUE TITLE
我想请问如何将vue3dLoader创建的canvas添加到我自己写的canvas里

### ISSUE THREAD

**Issue by exile-yy** [king2088/vue-3d-loader#20]
我用您的插件导入了几个模型 但是我的背景也是3d的 这导致我的页面上出现了两个canvas

**Comment by king2088** [comment]
> 我用您的插件导入了几个模型 但是我的背景也是3d的 这导致我的页面上出现了两个canvas

这个问题不在插件的讨论范围内，请自行寻找解决办法
