### ISSUE TITLE
Loading Model Issues

### ISSUE THREAD

**Issue by LukeRawlo** [king2088/vue-3d-loader#23]
Hello,

I am using this loader to load an obj file, however it is throwing multiple errors when i use exactly what the example shows. I'm doing a non-global import to a vue file, 

![image](https://user-images.githubusercontent.com/54494770/200450656-b664e02c-caa7-4c36-9ec8-df88b2023c27.png)

*the eslint comments are to disable unused imports

Nothing loads, and I get these 4 errors in my console. I've looked everywhere for a cause, however I've found nothing.

The obj file is in my public folder, nested in a models folder.

Thanks :)

![image](https://user-images.githubusercontent.com/54494770/200450401-1c35523c-bd35-4fff-ab81-d3913704aa1c.png)

**Comment by king2088** [comment]
> Hello,
> 
> I am using this loader to load an obj file, however it is throwing multiple errors when i use exactly what the example shows. I'm doing a non-global import to a vue file,
> 
> ![image](https://user-images.githubusercontent.com/54494770/200450656-b664e02c-caa7-4c36-9ec8-df88b2023c27.png)
> 
> *the eslint comments are to disable unused imports
> 
> Nothing loads, and I get these 4 errors in my console. I've looked everywhere for a cause, however I've found nothing.
> 
> The obj file is in my public folder, nested in a models folder.
> 
> Thanks :)
> 
> ![image](https://user-images.githubusercontent.com/54494770/200450401-1c35523c-bd35-4fff-ab81-d3913704aa1c.png)

If you use vue2.x, please install vue-3d-loader@1.2.12, if you use vue3, please install 2.x.x.
I saw this error is in create vue-3d-loader html element. Maybe your vue version and plug-in version are incorrect.

**Comment by LukeRawlo** [comment]
Hi Tony,

Thank you so much. You are a life saver! Works perfectly, greatly appreciated
