### ISSUE TITLE
请问3d文件是只能放到public里面吗，assets里面可以吗

### ISSUE THREAD

**Issue by quanliheng** [king2088/vue-3d-loader#24]

**Comment by king2088** [comment]
由于public与assets的区别在于是否经过webpack处理，public文件夹是原封不动复制过去，而assets则需要经过webpack的相关loader进行处理，而默认loader中没有配置3D文件后缀名，由此可能就导致了不能放到assets文件夹中，如果一定需要放到assets，请自行修改webpack配置，可采用file-loader对3d文件进行复制等操作。

**Comment by quanliheng** [comment]
那线上环境加载太慢有什么办法吗，我这边文件本身就比较大，到线上就要好几分钟

**Comment by king2088** [comment]
> 那线上环境加载太慢有什么办法吗，我这边文件本身就比较大，到线上就要好几分钟

可以了解一下3d文件压缩，各种3d模型轻量化或draco压缩

**Comment by quanliheng** [comment]
好的好的，谢谢
