### ISSUE TITLE
下载的npm包在测试项目中可以使用，但把npm包复制到业务项目中会报以下错误！

### ISSUE THREAD

**Issue by KyrieLuo** [king2088/vue-3d-loader#26]
请问有什么解决方法吗?束手无策![image](https://user-images.githubusercontent.com/41229754/203253630-32acd0d1-f4df-449c-9d28-e0f4253ae5f9.png)

**Comment by king2088** [comment]
> 请确保本地测试项目与业务项目的vue版本是否对应正确的vue-3d-loader版本。 `vue3请安装2.0.0及以上版本，vue2请安装1.x.x版本`

若未再提供多余的信息，我将在2天后关闭此issue
