### ISSUE TITLE
大佬vue2怎么自动旋转模型

### ISSUE THREAD

**Issue by yukangyang** [king2088/vue-3d-loader#27]

**Comment by yukangyang** [comment]
`<template>
  <div>
    <vue3dLoader
      :height="200"
      :width="200"
      @load="onLoad"
      :filePath="['/model/Duck/Duck.gltf']"
      :rotation="rotation"
    ></vue3dLoader>
  </div>
</template>
<script>
export default {
  nam: 'vuedtest',

  data() {
    return {
      rotation: {
        x: 0,
        y: 0,
        z: 0
      }
    }
  },
  methods: {
    onLoad() {
      this.rotate()
    },
    rotate() {
      requestAnimationFrame(rotate);
      rotation.z -= 0.01;
    }
  }
}
</script>
<style scoped>
</style>

`

**Comment by yukangyang** [comment]
```js
<template>
  <div>
    <vue3dLoader
      :height="200"
      :width="200"
      @load="onLoad"
      :filePath="['/model/Duck/Duck.gltf']"
      :rotation="rotation"
    ></vue3dLoader>
  </div>
</template>
<script>
export default {
  nam: 'vuedtest',

  data() {
    return {
      rotation: {
        x: 0,
        y: 0,
        z: 0
      }
    }
  },
  methods: {
    onLoad() {
      this.rotate()
    },
    rotate() {
      requestAnimationFrame(rotate);
      rotation.z -= 0.01;
    }
  }
}
</script>
<style scoped>
</style>

**Comment by yukangyang** [comment]
![Snipaste_2022-11-25_11-15-39](https://user-images.githubusercontent.com/92774734/203893348-25321ae8-dc56-4347-a621-03fa4e857380.png)

**Comment by yukangyang** [comment]
> _No description provided._

**Comment by yukangyang** [comment]
> _No description provided._

**Comment by king2088** [comment]
> ```js
> <template>
>   <div>
>     <vue3dLoader
>       :height="200"
>       :width="200"
>       @load="onLoad"
>       :filePath="['/model/Duck/Duck.gltf']"
>       :rotation="rotation"
>     ></vue3dLoader>
>   </div>
> </template>
> <script>
> export default {
>   name: 'vuedtest',
> 
>   data() {
>     return {
>       rotation: {
>         x: 0,
>         y: 0,
>         z: 0
>       }
>     }
>   },
>   methods: {
>     onLoad() {
>       this.rotate()
>     },
>     rotate() {
>       requestAnimationFrame(rotate);
>       rotation.z -= 0.01;
>     }
>   }
> }
> </script>
> <style scoped>
> </style>
> ```

代码中onLoad移除，把rotate()放到created()或mounted()生命周期中执行即可
更新后代码应该如下：
```vue
export default {
  name: 'vuedtest',

  data() {
    return {
      rotation: {
        x: 0,
        y: 0,
        z: 0
      }
    }
  },
  mounted() {
     this.rotate()
  },
  methods: {
    rotate() {
      requestAnimationFrame(rotate);
      rotation.z -= 0.01;
    }
  }
}
```

**Comment by yukangyang** [comment]
感谢感谢😁😁😁😘😘😘

**Comment by king2088** [comment]
> 

请查看关于vue2 的 demo代码：https://github.com/king2088/vue-3d-loader/blob/1.2.x/src/examples/rotate-model.vue

**Comment by king2088** [comment]
> 感谢感谢😁😁😁😘😘😘

成功了，记得给个start，谢谢
