### ISSUE TITLE
vue2 flex布局窗口尺寸变化，模型不会自适应变化

### ISSUE THREAD

**Issue by tudan110** [king2088/vue-3d-loader#28]
版本：1.2.12

flex 布局，控制模型所在 dom 的宽度（左侧 flex: 1, 右侧 flex: 0.41）

自己写 resize 监听父级 dom，dom只会变大，不会缩小，改成 百分比 布局，可以解决。

但是我看源码里有 resize 的监听，为啥不生效呢

![image](https://user-images.githubusercontent.com/29975209/205189946-8e097f8c-6c0a-4756-b623-9c211dc9d9e9.png)

**Comment by king2088** [comment]
> 版本：1.2.12 flex 布局 ![flex布局](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif) [ ![flex布局](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif) ](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif) [ ](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif)
> 
> flex 布局，控制模型所在 dom 的宽度（左侧 flex: 1, 右侧 flex: 0.41）
> 
> 自己写 resize 监听父级 dom，dom只会变大，不会缩小，改成 百分比 布局，可以解决。
> 
> 但是我看源码里有 resize 的监听，为啥不生效呢
> 
> ![image](https://user-images.githubusercontent.com/29975209/205017085-5eb0bfbf-15ff-45b4-92e3-090a795076ad.png)

请尝试在父元素的flex布局中增加overflow: hidden;看看能不能解决问题，经过我的测试应该是可以的
```
.main{
  display: flex;
}
.left-3d{
  flex: 1;
  overflow: hidden;
}
.right-menu{
  flex: 0.5;
}
```
vue-3d-loader的使用
```html
<template>
  <div class="main">
    <div class="left-3d">
      <vue3dLoader
        filePath="/models/collada/stormtrooper/stormtrooper.dae"
        :cameraPosition="{ x: 10, y: 0, z: -10 }"
      />
    </div>
    <div class="right-menu">asdasdasdsadsadasdasdasdas</div>
  </div>
</template>
```

**Comment by king2088** [comment]
> 版本：1.2.12 flex 布局 ![flex布局](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif) [ ![flex布局](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif) ](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif) [ ](https://user-images.githubusercontent.com/29975209/205015598-636c0b02-6cad-45fe-9083-7279ec59cb2c.gif)
> 
> flex 布局，控制模型所在 dom 的宽度（左侧 flex: 1, 右侧 flex: 0.41）
> 
> 自己写 resize 监听父级 dom，dom只会变大，不会缩小，改成 百分比 布局，可以解决。
> 
> 但是我看源码里有 resize 的监听，为啥不生效呢
> 
> ![image](https://user-images.githubusercontent.com/29975209/205017085-5eb0bfbf-15ff-45b4-92e3-090a795076ad.png)

请尝试在父元素的flex布局中增加overflow: hidden;看看能不能解决问题，经过我的测试应该是可以的
```
.main{
  display: flex;
}
.left-3d{
  flex: 1;
  overflow: hidden;
}
.right-menu{
  flex: 0.5;
}
```
vue-3d-loader的使用
```html
<template>
  <div class="main">
    <div class="left-3d">
      <vue3dLoader
        filePath="/models/collada/stormtrooper/stormtrooper.dae"
        :cameraPosition="{ x: 10, y: 0, z: -10 }"
      />
    </div>
    <div class="right-menu">asdasdasdsadsadasdasdasdas</div>
  </div>
</template>
```

**Comment by tudan110** [comment]
ok，谢谢，试了一下，是我自己没控制好外层 div
