### ISSUE TITLE
Unable to load any of file (404 Not Found or undefined object)

### ISSUE THREAD

**Issue by gabrielgriesser** [king2088/vue-3d-loader#29]
It's been 5 hours now that I'm looking for how to manage a file with your VueJS component.
I use Vue3 and vue-3d-loader 2.1.3

I am trying to load an .OBJ, .GLTF or .MTL file. Whether it's in the **public folder**, **as an assets** or even **loaded via an input form**, I always get EITHER a 404 error OR an exception (`Cannot read properties of undefined (reading 'split')`)

Has anyone had this problem before?

![image](https://user-images.githubusercontent.com/26295873/205846805-22364e69-8186-4c7d-95ed-ddc3db54e80d.png)

**Comment by Smartich0ke** [comment]
Can you provide a snippet of the code you are using to load the component and the file? It look like either the file is not in the right place or that folder can't be accessed through the site URL. Try pasting `http://localhost:8080/part-details/TEST.obj`  into the address bar of your browers and checking that it downloads the file.

**Comment by king2088** [comment]
> It's been 5 hours now that I'm looking for how to manage a file with your VueJS component. I use Vue3 and vue-3d-loader 2.1.3
> 
> I am trying to load an .OBJ, .GLTF or .MTL file. Whether it's in the **public folder**, **as an assets** or even **loaded via an input form**, I always get EITHER a 404 error OR an exception (`Cannot read properties of undefined (reading 'split')`)
> 
> Has anyone had this problem before?
> 
> ![image](https://user-images.githubusercontent.com/26295873/205846805-22364e69-8186-4c7d-95ed-ddc3db54e80d.png)

- Please ensure `http://localhost:8080/part-details/TEST.obj` file can be downloaded through the browser.
- vue-3d-loader component only support **url path**, not support input file. If you want load input file, may be you need upload the file to server and get the file url path.
- In the local environment, files must be placed in the **public directory**. Such as your file http://localhost:8080/part-details/TEST.obj, the TEST.obj file must in /public/part-details/ directory. **Not support assets dirctory**.

**Comment by gabrielgriesser** [comment]
Okay it works ! 

I had to remove the camera position from vue3dloader component so I can see the object !

Thank you very much to all :) Have a nice day

**Comment by king2088** [comment]
> Okay it works !
> 
> I had to remove the camera position from vue3dloader component so I can see the object !
> 
> Thank you very much to all :) Have a nice day

That's great. If this plug-in can help you. Please give me a star. thanks
