### ISSUE TITLE
关于鼠标拖拽模型卡顿的问题

### ISSUE THREAD

**Issue by maxoyed** [king2088/vue-3d-loader#3]
您好，我使用您的组件加载本地的gltf模型文件，在浏览器上预览时，用鼠标拖拽模型旋转或移动模型，会经常出现卡顿的现象，请问是怎么回事呢？

**Comment by king2088** [comment]
> 您好，我使用您的组件加载本地的gltf模型文件，在浏览器上预览时，用鼠标拖拽模型旋转或移动模型，会经常出现卡顿的现象，请问是怎么回事呢？

感谢你的使用与支持，出现加载卡顿的情况，请检查以下几个问题：
1、模型是否过大，一般情况，超过100M以上的模型直接加载可能会出现卡顿的情况。
2、电脑硬件太差，电脑硬件太差也会导致卡顿的问题。
3、查看电脑CPU与内存及GPU的使用情况是否出现100%等情况。
