### ISSUE TITLE
请问怎么加载两个相同的模型呢，我这边加载多个相同的模型就只显示一个，用的是2.0.9版本

### ISSUE THREAD

**Issue by quanliheng** [king2088/vue-3d-loader#30]

**Comment by king2088** [comment]
只显示一个是因为你加载的模型位置一致，导致了两个模型重叠了，你可以分别给每一个模型都单独设置一下position就可以看到两个模型了

**Comment by quanliheng** [comment]
这个我有设置，但是只显示了一个，位置不变换一个不一样的模型就可以出来

**Comment by king2088** [comment]
> 这个我有设置，但是只显示了一个，位置不变换一个不一样的模型就可以出来

可以通过复制两个相同3D文件（文件名不一样，如x.fbx 、x-copy.fbx），加载的时候，分别加载2个文件。如果同时加载同一个文件2次，threeJS会将他们的position都设置为一样的，虽然加载成功了，但是两个模型的位置一直保持一致重叠。

当然使用这样的方式进行加载多个相同模型确实会存在性能及加载速度慢（因为每个模型都是一个文件，没加载一次都需要下载一次）的问题，后期我会再增加一个copy或clone属性，通过copy及clone的方式直接创建新的相同模型，而无需从filePath中引入多个相同文件

**Comment by quanliheng** [comment]
好的，谢谢
