### ISSUE TITLE
Refresh (watch) labels

### ISSUE THREAD

**Issue by primopc** [king2088/vue-3d-loader#32]
is it possible refresh the model when i add new items to labels ?

<template>

 <div>
<div>
   <button @click='asigna'>
     prueba
   </button> 
</div>  
   <vue3dLoader
    filePath = '../assets/3.glb'
    :position = '{x:0, y:0.8, z:0}'
    :scale= "{ x: 0.5, y: 0.5, z: 0.5 }"
    :autoPlay = "true"
    :height='900'
   outputEncoding="sRGB"
    :labels='labelstmp'
    @click="ev"
    :intersectRecursive="true"
  :cameraPosition="{ x: 0, y: 0, z: 2 }"
   >
  </vue3dLoader>
  {{labels}}
  </div>
</template>

<script>
export default {
  data() {
    return {
      filepath: '',
      labels:[],
      labelstmp:[],
      newlabel:{
            image: "./assets/1.png",
            position: { x: -0.5, y: 1, z: 0 },
            scale: { x: 0.6, y: 0.6, z: 0.6 },
            sid: null, // custom id
      }
    };
  },

 mounted() {
      //this.initCharts()
   this.labelstmp = [

  {
    image: "./assets/1.png",
    position: { x: -0.5, y: 1, z: 0 },
    scale: { x: 0.6, y: 0.6, z: 0.6 },
    sid: 1, // custom id
  },
  {
    image: "./assets/2.png",
    position: { x: 0.5, y: 1.2, z: 0.2 },
    scale: { x: 1, y: 1, z: 1 },
    sid: 2,
  },

  {
    text: "I'm Text Label",
    position: { x: 1, y: 0, z: 0.1 },
    scale: { x: 1, y: 1, z: 1 },
    textStyle: {
      fontFamily: "Arial",
      fontSize: 10,
      fontWeight: 200,
      lineHeight: 1,
      color: "#ffffff",
      borderWidth: 1,
      borderRadius: 2,
      borderColor: "#000000",
      backgroundColor: "rgba(0,0,0,1)",
 

    },
    sid: 3, 
  },
  {
    image: "./assets/1.png",
    position: { x: 0.13, y: 1.75, z: 0.2 },
    scale: { x: 0.08, y: 0.08, z: 0 },
    sid: 4, // custom id
  },
 

];

    },
  methods: {
     ev(MouseEvent,  intersected) {
        console.log(intersected.object.sid)
        console.log(intersected)
        if (intersected){
          this.newlabel.position.x = intersected.point.x
          this.newlabel.position.y = intersected.point.y
          this.newlabel.position.z = 0.2
          this.newlabel.sid = this.labels.length  
          this.labels.push(this.newlabel)
          console.log(this.labels)
        }
      },
      asigna(){
        this.labels = this.labelstmp
      }

  }
};
</script>

**Comment by king2088** [comment]
> 

Current version is not watch labels, so is'nt refresh or change labels attribute
