### ISSUE TITLE
【疑问】vue2和vu3

### ISSUE THREAD

**Issue by JaneYork** [king2088/vue-3d-loader#34]
- vue2和vue3是同步更新的吗，API啥的应该是通用的吗？
- 1.x和2.x是同步更新的吗？1.x有draco压缩吗？
- 怎么贴图啊，比如FBX模型，需要很多PNG贴图  @king2088

**Comment by king2088** [comment]
是的，都是同步更新的。

**Comment by king2088** [comment]
> - vue2和vue3是同步更新的吗，API啥的应该是通用的吗？
> - 1.x和2.x是同步更新的吗？1.x有draco压缩吗？

必须的

**Comment by JaneYork** [comment]
> > * vue2和vue3是同步更新的吗，API啥的应该是通用的吗？
> > * 1.x和2.x是同步更新的吗？1.x有draco压缩吗？
> 
> 必须的

如何贴图呢？

**Comment by king2088** [comment]
> > > * vue2和vue3是同步更新的吗，API啥的应该是通用的吗？
> > > * 1.x和2.x是同步更新的吗？1.x有draco压缩吗？
> > 
> > 必须的
> 
> 如何贴图呢？textureImage参数直接`按顺序`放图片PNG地址吗

是的，API有写的很清楚

**Comment by JaneYork** [comment]
> > > > * vue2和vue3是同步更新的吗，API啥的应该是通用的吗？
> > > > * 1.x和2.x是同步更新的吗？1.x有draco压缩吗？
> > > 
> > > 
> > > 必须的
> > 
> > 
> > 如何贴图呢？textureImage参数直接`按顺序`放图片PNG地址吗
> 
> 是的，API有写的很清楚

贴图了，为啥没显示出来，还是黑乎乎一片，有可能是啥原因呢？  需要定位还是需要指定图片名称？还是需要旋转啥的操作？
```
        <vue3dLoader
          :height="410"
          :showFps="true"
          :filePath="['/3d/demo/92shouqiang.FBX']"
          :mtlPath="[null, null, null]"
          :textureImage="shouqiang.textureImage"
        ></vue3dLoader>

      shouqiang: {
        textureImage: [
          '/3d/demo/shouqiang/img.png',
          '/3d/demo/shouqiang/img_1.png',
          '/3d/demo/shouqiang/img_2.png',
          '/3d/demo/shouqiang/img_3.png',
          '/3d/demo/shouqiang/img_4.png',
        ]
      }
```

**Comment by king2088** [comment]
> > > > > * vue2和vue3是同步更新的吗，API啥的应该是通用的吗？
> > > > > * 1.x和2.x是同步更新的吗？1.x有draco压缩吗？
> > > > 
> > > > 
> > > > 必须的
> > > 
> > > 
> > > 如何贴图呢？textureImage参数直接`按顺序`放图片PNG地址吗
> > 
> > 是的，API有写的很清楚
> 
> 贴图了，为啥没显示出来，还是黑乎乎一片，有可能是啥原因呢？  需要定位还是需要指定图片名称？还是需要旋转啥的操作？
> ```
>         <vue3dLoader
>           :height="410"
>           :showFps="true"
>           :filePath="['/3d/demo/92shouqiang.FBX']"
>           :mtlPath="[null, null, null]"
>           :textureImage="shouqiang.textureImage"
>         ></vue3dLoader>
> 
>       shouqiang: {
>         textureImage: [
>           '/3d/demo/shouqiang/img.png',
>           '/3d/demo/shouqiang/img_1.png',
>           '/3d/demo/shouqiang/img_2.png',
>           '/3d/demo/shouqiang/img_3.png',
>           '/3d/demo/shouqiang/img_4.png',
>         ]
>       }
> ```
> 
> <img width="873" alt="image" src="https://user-images.githubusercontent.com/29787967/212599544-a86a222c-b385-47a1-8a24-468ecbca8111.png">
> 

首先，查看一下模型是否自带贴图，如果自带贴图，那贴图需要与模型放置在同一个文件夹内。
如果使用的是png图片作为贴图，那么一个模型文件仅可以采用一张图片贴图。mtl也一样。

**Comment by king2088** [comment]
超过7天无新回复则关闭
