### ISSUE TITLE
我加入stl模型时，模型都是白色的，能不能加个配置设置模型颜色比如灰色

### ISSUE THREAD

**Issue by 714871549** [king2088/vue-3d-loader#35]
![image](https://user-images.githubusercontent.com/20897369/212799866-949bb76d-b731-4283-be89-2230e96d574a.png)
我加入stl模型时，模型都是白色的，能不能加个配置设置模型颜色比如灰色，比如我这图

**Comment by king2088** [comment]
> ![image](https://user-images.githubusercontent.com/20897369/212799866-949bb76d-b731-4283-be89-2230e96d574a.png)
> 我加入stl模型时，模型都是白色的，能不能加个配置设置模型颜色比如灰色，比如我这图
> 
如果需要颜色，建议转换成其他格式进行使用，如.dae/.fbx/.gltf/.glb/.obj等包含颜色属性的3D模型文件。

`STL文件格式，是3D System公司于1988年制定的一个结构协议，是一种快速原型制造服务的三维图形文件格式。
       STL文件由许多三角形面片组成，每个三角形面片由三个顶点的三维坐标和三角形面片的法线向量描述。STL文件仅描述三维物体的表面几何形状，没有颜色、材质贴图等其他属性。`

**Comment by king2088** [comment]
超过7天无新回复则关闭
