### ISSUE TITLE
vue2.6.14使用1.2.12版本引入fbx格式的模型报错this.loader.setMaterials is not a function

### ISSUE THREAD

**Issue by PoorlifeAyu** [king2088/vue-3d-loader#36]

**Comment by king2088** [comment]
vue2请使用1.x.x版本

**Comment by king2088** [comment]
请帖出相关代码及错误信息

**Comment by PoorlifeAyu** [comment]
![Snipaste_2023-02-09_12-14-11](https://user-images.githubusercontent.com/85815933/217716247-fd0ee1b9-d138-4f90-9eec-5065ce699673.png)
![Snipaste_2023-02-09_12-13-50](https://user-images.githubusercontent.com/85815933/217716255-5e338234-6d75-44eb-9473-057da7ea5218.png)
![Snipaste_2023-02-09_12-14-30](https://user-images.githubusercontent.com/85815933/217716251-4213df3a-4e5d-4a3e-93a1-4e8391fbc050.png)

**Comment by king2088** [comment]
> 
你可以尝试不加载mtl材质，看能否加载出fbx模型。我觉得可能是你的目录问题导致的，请尝试在浏览器中输入http://localhost:[prot]/models/baizhi/baizhi.fbx（把[port]更换成自己的项目端口号），看会不会出现下载fbx，如果不会下载，并且出现404的情况。请将你的models文件夹放到public文件夹下面

**Comment by PoorlifeAyu** [comment]
换到public里面不加载mtl材质就可以，但是只要尝试加载mtl材质还是会出现相同的报错

**Comment by king2088** [comment]
> 

细看了下，科普一下：
- FBX格式支持法线和贴图坐标。贴图以及坐标信息都可以存入FBX文件中，文件导入后不需要手动指认贴图以及调整贴图坐标。
- OBJ文件支持法线和贴图坐标。OBJ只能保存贴图坐标信息，贴图需要手动重新指认，但不需要再调整贴图坐标。

因此，想要使用mtl材质，请采用OBJ模型

**Comment by PoorlifeAyu** [comment]
了解了，那如果材质是tga格式的怎么给模型加上tga格式材质呢

**Comment by king2088** [comment]
> 了解了，那如果材质是tga格式的怎么给模型加上tga格式材质呢

暂时不支持tga材质

**Comment by PoorlifeAyu** [comment]
好的，谢谢
