### ISSUE TITLE
一个fbx模型能够贴多个jpg的图片纹理吗？

### ISSUE THREAD

**Issue by PoorlifeAyu** [king2088/vue-3d-loader#37]
![Snipaste_2023-02-13_14-05-29](https://user-images.githubusercontent.com/85815933/218383083-6b63bcd3-6f80-4d09-812f-5d45f4af3471.png)
![Snipaste_2023-02-13_14-05-56](https://user-images.githubusercontent.com/85815933/218383105-c1a8d6ff-ae9c-4a37-95f9-4bceacae8dba.png)
我这样写后一个纹理也没有贴成功，控制台还报错了

**Comment by king2088** [comment]
> ![Snipaste_2023-02-13_14-05-29](https://user-images.githubusercontent.com/85815933/218383083-6b63bcd3-6f80-4d09-812f-5d45f4af3471.png) ![Snipaste_2023-02-13_14-05-56](https://user-images.githubusercontent.com/85815933/218383105-c1a8d6ff-ae9c-4a37-95f9-4bceacae8dba.png) 我这样写后一个纹理也没有贴成功，控制台还报错了

请仔细阅读使用文档，目前一个3D模型对应一种材质，不得一对多
