### ISSUE TITLE
请问为什么线上的点击事件获取不到intersects，本地可以获取到，版本号是1.2.7

### ISSUE THREAD

**Issue by 254840130** [king2088/vue-3d-loader#39]

**Comment by king2088** [comment]
请贴出相关代码

**Comment by 254840130** [comment]
<vue3dLoader
    :width="screenWidth"
    :height="screenHeight"
    :filePath="filePaths"
    backgroundColor="black"
    @click="onclick"
></vue3dLoader>

<script>
export default {
  data() {
    return {
      filePaths: [`static/xinfengji.ply`, `static/wushuikeng.ply` ],
      screenHeight: window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight,
      screenWidth: window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth,
    }
  },
  methods: {
    onclick(event, intersected) {
      console.log('测试',event, intersected)
    }
  }
}

**Comment by king2088** [comment]
> <vue3dLoader :width="screenWidth" :height="screenHeight" :filePath="filePaths" backgroundColor="black" @click="onclick"
> 
> > 
> 
> <script> export default { data() { return { filePaths: [`static/xinfengji.ply`, `static/wushuikeng.ply` ], screenHeight: window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight, screenWidth: window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth, } }, methods: { onclick(event, intersected) { console.log('测试',event, intersected) } } } </script>

如果是你打包成了生产环境的JS发布到线上，那么生产代码会把你的console.log代码移除，因此你在生产环境下是无法看到控制台输出的内容。

**Comment by 254840130** [comment]
控制台是可以看到console.log的，event有数据，intersected是null

**Comment by king2088** [comment]
> 控制台是可以看到console.log的，event有数据，intersected是null

请仔细查看API文档中关于`intersectRecursive`参数的说明

**Comment by king2088** [comment]
并且，将vue-3d-loader `1.2.7` 版本升级到最新版本 `1.2.13`，方可支持`intersectRecursive`参数

**Comment by 254840130** [comment]
解决了，谢谢你

**Comment by king2088** [comment]
> 解决了，谢谢你

OK！顺手点下start支持下。

**Comment by JaneYork** [comment]
怎么在大数据界面，点击模型弹窗显示详情，详情页能用动态数据 @254840130
