### ISSUE TITLE
依赖下载完成后，在main.js中引入时项目报错

### ISSUE THREAD

**Issue by wang0301-wang** [king2088/vue-3d-loader#44]
Vue版本是2.5.2，下载依赖版本为1.2.8
![image](https://user-images.githubusercontent.com/84119696/220814820-3204da9c-3b8c-4371-898a-e379297b9d7d.png)

**Comment by wang0301-wang** [comment]
![image](https://user-images.githubusercontent.com/84119696/220814944-e50258d7-87a3-47ea-adae-3addf966864f.png)

**Comment by king2088** [comment]
把报错信息也贴上来看看嘛
