### ISSUE TITLE
多模型展示单独控制

### ISSUE THREAD

**Issue by sea-20** [king2088/vue-3d-loader#45]
大佬，您好！
        想请问一下该插件能否支持在多模型展示的基础上，对其中的单个模型进行拖拽，缩放，旋转等操作展示？
        还想请问在web端展示3D模型（.stl）对文件本身大小有什么限制吗？一般电脑的内存和浏览器能支撑上百MB的模型文件展示吗？加载速度会不会很慢，谢谢！

**Comment by king2088** [comment]
你说的范畴已经属于3D编辑器了，本插件仅用于展示3D模型，不能进行模型编辑，如需了解3D模型编辑，可以参阅threeJS官方提供的3D模型编辑器https://threejs.org/editor/
