### ISSUE TITLE
access to 3d object Meshes

### ISSUE THREAD

**Issue by masoudabdan** [king2088/vue-3d-loader#46]
Hi. I need to list or access to meshes in a loaded 3d file. to change color or hide some meshes. how can i do this?

**Comment by king2088** [comment]
You can use events get 3d object data, and you can change the color. [Change 3d model color example](https://king2088.github.io/vue-3d-loader-docs/guide/example/events.html).
If you want hide/show some meshes or model, may be can use events same. Use it look like
```vue
<template>
  <vue3dLoader
    filePath="/models/ply/Lucy100k.ply"
    @mousemove="onMouseMove"
    :cameraPosition="{ x: 0, y: 0, z: -2500 }"
  />
</template>
<script setup lang="ts">
import { vue3dLoader } from "vue-3d-loader";
import { ref } from "vue";
const object = ref(null);
function onMouseMove(event: MouseEvent, intersected: any) {
  if (intersected) {
    object.value = intersected.object;
    (object.value as any).object.visible=false // hide model
    (object.value as any).material.visible=false; // hide material
  }
}
</script>
```

**Comment by king2088** [comment]
No response after 7 days, closed
