### ISSUE TITLE
can't add to nextcloud app 

### ISSUE THREAD

**Issue by aminvandh** [king2088/vue-3d-loader#47]
I tried to add this into nextcloud project but it leaves me with warnings:
`WARNING in ./node_modules/vue-3d-loader/dist/vue-3d-loader.esm.js 42057:13-22                                           export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports:`

`WARNING in ./node_modules/vue-3d-loader/dist/vue-3d-loader.esm.js 42057:26-44                                           export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports:`

`WARNING in ./node_modules/vue-3d-loader/dist/vue-3d-loader.esm.js 42062:8-26                                            export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports:`

**Comment by king2088** [comment]
What vue-3d-loader version and nuxt version are you using?
Use vue-3d-loader in nuxt2, you need install version 1.2.14. 
If you use nuxt2, example:
- In nuxt2 plugins directory create `vue-3d-loader-plugin.js`
```
import Vue from 'vue'
import vue3dLoader from 'vue-3d-loader'
Vue.use(vue3dLoader)

```
- Add the plugin to `nuxt.config.js`
```
plugins: [
    { src: '@/plugins/vue-3d-loader-plugin', mode: 'client' }
  ],
```
- Use in vue file
```html
<!-- the 3d model files must be placed in static folders  -->
<vue3dLoader :file-path="'/models/gltf/DamagedHelmet.gltf'" />
```

**Comment by aminvandh** [comment]
Thanks, nextcloud uses Vue 2.7 and i don't have nuxt installed. still can load model with new vue project (v3.*) but not with this one

**Comment by king2088** [comment]
You can try install vue-3d-loader version **1.2.14**  in your nextcloud project. In the vue2 must use vue-3d-loader@1.x.x, in the vue3 use vue-3d-loader@2.x.x .

**Comment by aminvandh** [comment]
Thanks for help, errors are gone, but nothing shows up, its maybe my issue.
src/main.js:
`import { generateFilePath } from '@nextcloud/router'

import App from './App'
import vue3dLoader from 'vue-3d-loader'
import Vue from 'vue'
// eslint-disable-next-line
__webpack_public_path__ = generateFilePath(appName, '', 'js/')

Vue.mixin({ methods: { t, n } })
Vue.use(vue3dLoader);
export default new Vue({
	el: "#content",
	render: h => h(App),
	
})`

**Comment by king2088** [comment]
> Thanks for help, errors are gone, but nothing shows up, its maybe my issue. src/main.js:
> 
> `import App from './App'` `import vue3dLoader from 'vue-3d-loader'` `import Vue from 'vue'` `// eslint-disable-next-line` `__webpack_public_path__ = generateFilePath(appName, '', 'js/')`
> 
> `Vue.mixin({ methods: { t, n } })` `Vue.use(vue3dLoader);` `export default new Vue({` `el: "#content",` `render: h => h(App),`
> 
> `})`

Set height/width or scale

**Comment by king2088** [comment]
> Thanks for help, errors are gone, but nothing shows up, its maybe my issue. src/main.js:
> 
> `import App from './App'` `import vue3dLoader from 'vue-3d-loader'` `import Vue from 'vue'` `// eslint-disable-next-line` `__webpack_public_path__ = generateFilePath(appName, '', 'js/')`
> 
> `Vue.mixin({ methods: { t, n } })` `Vue.use(vue3dLoader);` `export default new Vue({` `el: "#content",` `render: h => h(App),`
> 
> `})`

Set height/width or scale. More info you can view document https://king2088.github.io/vue-3d-loader-docs/guide/api.html

**Comment by king2088** [comment]
Your glb file must be accessible through a url. It is recommended to place the file in the public or static directory.

**Comment by aminvandh** [comment]
<a href="https://freeimage.host/i/HhBdfA7"><img src="https://iili.io/HhBdfA7.md.png" alt="HhBdfA7.md.png" border="0"></a>

**Comment by aminvandh** [comment]
Here is debug console
<a href="https://freeimage.host/i/HhBq3Sj"><img src="https://iili.io/HhBq3Sj.md.png" alt="HhBq3Sj.md.png" border="0"></a>

**Comment by king2088** [comment]
If your glb file in the public directory, the `filePath` don't add '/public/', look like this:
```
<vue-3d-loader filePath="/house.glb"/>
```

**Comment by aminvandh** [comment]
path is fine, i think its a router issue, which won't let that access

**Comment by king2088** [comment]
> path is fine, i think its a router issue, which won't let that access

Your glb file http url is 404(not found)，the url not access, so you need a glb file path that can be accessed through a url. In the vue project project, the public directory is not processed by webpack, if your build your front-end project, the public directory all files is in root directory. So in the vue  your want access your public directory files, you can directly access the files in the root directory.
Of course, most of the time, your glb files are stored directly on an http server, so you can simply place your glb files on another http server that can be accessed through a url, such as using http server locally.

**Comment by king2088** [comment]
I see your gbl file url is `http:localhost:8080/index.php/apps/public/house.glb`, I think your glb file url may be is `http://localhost:8080/apps/public/house.glb`. So you can use your browser access `http://localhost:8080/apps/public/house.glb`, if can download the `house.glb`, you can try this code:
```
<vue-3d-loader filePath="http://localhost:8080/apps/public/house.glb"/>
```

**Comment by aminvandh** [comment]
other tags like <img> work well with files in any directory.

**Comment by aminvandh** [comment]
BTW thank you BTW, i used external link to point and it worked well
<a href="https://freeimage.host/i/HhCnxEP"><img src="https://iili.io/HhCnxEP.md.png" alt="HhCnxEP.md.png" border="0"></a>
