### ISSUE TITLE
vue3+js，使用"vue-3d-loader": "^2.1.5"版本无法加载模型

### ISSUE THREAD

**Issue by SLN178716** [king2088/vue-3d-loader#49]
![image](https://user-images.githubusercontent.com/40198398/230874294-ee3773de-9b7f-4e72-a1a6-edc5862cd3b0.png)
![image](https://user-images.githubusercontent.com/40198398/230874536-ef751dbc-5066-4565-a209-0aee74358844.png)

**Comment by king2088** [comment]
> ![image](https://user-images.githubusercontent.com/40198398/230874294-ee3773de-9b7f-4e72-a1a6-edc5862cd3b0.png) ![image](https://user-images.githubusercontent.com/40198398/230874536-ef751dbc-5066-4565-a209-0aee74358844.png)

请提供一下vue3的版本号

**Comment by SLN178716** [comment]
版本是“3.2.38”
![image](https://user-images.githubusercontent.com/40198398/231031663-612441b2-fd69-43d7-a6d2-5bdff223a736.png)

**Comment by king2088** [comment]
经过测试，并未发现有你锁描述的warn出现，但是根据你的warn的提示，看似是生命周期的问题。如果你的页面中存在生命周期onMounted等声明周期在setup中，请将跟生命周期有关的函数都写到script的前面，如下：
```vue
<script setup>
import { onMounted } from 'vue'
// 将onMounted等生命周期函数，置于import下
onMounted(() => {....})
// 其它代码
</script>
```

**Comment by king2088** [comment]
超过7天无回应，关闭
