### ISSUE TITLE
vue2 加载进度问题以及多个模型多个事件问题

### ISSUE THREAD

**Issue by Hjl122457** [king2088/vue-3d-loader#53]
加载进度好像获取不到total一直为0
![image](https://user-images.githubusercontent.com/89336009/231952976-abfac104-9c9e-4431-aba9-22db9b6ebe85.png)
还有大哥我问一下我有多个模型，每个模型的事件都有对应的事件能支持嘛

**Comment by king2088** [comment]
> 加载进度好像获取不到total一直为0 ![image](https://user-images.githubusercontent.com/89336009/231952976-abfac104-9c9e-4431-aba9-22db9b6ebe85.png) 还有大哥我问一下我有多个模型，每个模型的事件都有对应的事件能支持嘛

1、total为0的问题，是由于webpack本地服务导致的。请将你的模型放到外部服务器上（不是wenpack启动的http服务，如npm安装使用http-server或者nginx）。
2、没有明白你说的模型事件问题，请仔细描述下你的问题

**Comment by Hjl122457** [comment]
如果我有多个模型，每个模型都有一个标识，鼠标移入那个模型，那个模型的标识高亮这个可以实现嘛?

**Comment by king2088** [comment]
好好看文档，再好好看threeJS，肯定可以的。

**Comment by Hjl122457** [comment]
好的
