### ISSUE TITLE
设置环境光后模型变黑

### ISSUE THREAD

**Issue by CHAUMET** [king2088/vue-3d-loader#55]
vue3: 3.2.13  vue-3d-loader：2.1.5
如题， 模型导入不设置光线的前提下只有特定角度有光，设置环境光后模型黑掉了。
```javascript
<template>
  <div>
    <vue3dLoader
      filePath="04.gltf"
      :height="850"
      :lights="lights"
      backgroundColor="#ccc"
    />
  </div>
</template>

<script setup>
import { ref } from "vue";
import { vue3dLoader } from "vue-3d-loader";
const lights = ref([
  {
    type: "AmbientLight",
    color: "white",
  },
]);
</script>
```

![image](https://user-images.githubusercontent.com/22586470/233299024-9e462466-2c88-4503-9e75-56934463597a.png)

**Comment by king2088** [comment]
> 

设置outputEncoding为“sRGB”即可，详细案例代码，可以参考https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/load-multiple-models.html

**Comment by king2088** [comment]
超过7天无回应，关闭
