### ISSUE TITLE
整个模型中包含多个不同设备的模型编码，能单独给某个设备上颜色吗？

### ISSUE THREAD

**Issue by LSWleecc** [king2088/vue-3d-loader#60]
整个模型文件中包含多个不同设备模型及对应的模型编码，能单独给某个设备上颜色吗？

**Comment by king2088** [comment]
可以参考这个案例，看能否拿到你要的模型数据，并改变其颜色https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/events.html

**Comment by Eirice01** [comment]
模型事件触发后，intersected 对象始终为null   intersected对象获取的标准是什么啊 老哥。看了three源码中的交互事件 使用的Raycaster 对象转换的。 您这边的案例中只有Lucy100k.ply 它可以获取到，且filePath 不能为数组。
