### ISSUE TITLE
gltf/glb穿模问题.

### ISSUE THREAD

**Issue by Sercl** [king2088/vue-3d-loader#61]
![image](https://user-images.githubusercontent.com/35843500/235266537-34d7a72b-bfa5-468e-ad24-1d32c44cecef.png)

很感谢大大提供的组件。但是用起来发现gltf/glb有穿模问题，而其他FBX，OBJ的模型则没有这个问题。视角必须拉远才行，官网的gltf示例也有，尝试过修改摄像机位置，模型位置，缩放等操作都无效。

穿模异常：
![image](https://user-images.githubusercontent.com/35843500/235266722-b156e7cd-4c2e-4a44-9843-b2a049dca029.png)
正常：
![image](https://user-images.githubusercontent.com/35843500/235266750-458dc217-8afc-4856-a2c7-2d219fe8c6bd.png)

这个还有什么办法可以解决吗？非常感谢。

**Comment by king2088** [comment]
穿模的问题，目前暂时没有更好的解决方法。但是可以从`限制相机向内外移动`上解决穿模的问题。下一版本即将添加[minDistance](https://threejs.org/docs/index.html#examples/zh/controls/OrbitControls.minDistance)及[maxDistance](https://threejs.org/docs/index.html#examples/zh/controls/OrbitControls.maxDistance)来限制相机向内外移动的限制，从而阻止相机进入模型内部
