### ISSUE TITLE
获取模型对象信息目前至于ply的可以，且filePath 为数组时也无法获取（包含ply）

### ISSUE THREAD

**Issue by Eirice01** [king2088/vue-3d-loader#62]
模型事件触发后，intersected 对象始终为null intersected对象获取的标准是什么啊 老哥。看了three源码中的交互事件 使用的Raycaster 对象转换的。 您这边的案例中只有Lucy100k.ply 它可以获取到，且filePath 不能为数组。

**Comment by king2088** [comment]
> 模型事件触发后，intersected 对象始终为null intersected对象获取的标准是什么啊 老哥。看了three源码中的交互事件 使用的Raycaster 对象转换的。 您这边的案例中只有Lucy100k.ply 它可以获取到，且filePath 不能为数组。

查看api中`intersectRecursive`的设置
