### ISSUE TITLE
组件在UNIApp中使用报错

### ISSUE THREAD

**Issue by xinhaojie** [king2088/vue-3d-loader#64]
大佬，UNIAPP能用吗，我在项目中引入，然后使用时好多报错，一个是单文件import时提示找不到要导入的组件，我看安装的目录下没有.vue文件，没办法绝对路径导入。在全局入口导入后，使用时报错：

[Vue warn]: Unhandled error during execution of mounted hook
at <Vue3dLoaderkey=2width=350height=200 ...>
at <Face3DPagekey=3>
at <Index__pageId=1__pagePath="pages/index/index"__pageQuery={} ...>
15:59:10.110 TypeError: Cannot set property 'width' of null
15:59:10.119 mtl file path:, _doc/uniapp_temp/16836191487991.mtl at pages/face_3D/face_3D.vue:236
15:59:10.124 [Vue warn]: Unhandled error during execution of watcher callback
at <Vue3dLoaderkey=2width=350height=200 ...>
at <Face3DPagekey=3>
at <Index__pageId=1__pagePath="pages/index/index"__pageQuery={} ...>
15:59:10.129 TypeError: Cannot read property 'setSize' of null
15:59:10.134 texture_img file path:, _doc/uniapp_temp/16836191487992.png at pages/face_3D/face_3D.vue:245
15:59:10.140 obj file path:, _doc/uniapp_temp/16836191487980.obj at pages/face_3D/face_3D.vue:227
15:59:10.145 [Vue warn]: Unhandled error during execution of watcher callback
at <Vue3dLoaderkey=2width=350height=200 ...>
at <Face3DPagekey=3>
at <Index__pageId=1__pagePath="pages/index/index"__pageQuery={} ...>
15:59:10.149 TypeError: Cannot read property 'removeEventListener' of undefined

**Comment by king2088** [comment]
并未在uniapp中使用和测试过，之前有一个issue也是关于uniapp的，如果无法使用可能也就无法使用了，暂时没有特殊的解决方法
