### ISSUE TITLE
怎么动态修改textureImage， 赋值变了，但是模型并没有

### ISSUE THREAD

**Issue by zhangxu1123** [king2088/vue-3d-loader#65]
``<vue3dLoader
            filePath="http://10.77.10.72:3000/upload/model.DAE"
            
            :cameraPosition="{ x: 0, y: 0, z: 0 }"
            :width="500"
            :height="500"
            :intersectRecursive="true"
            :textureImage="textureImage"
        />
<button @click="changeImage">
            textureImage
          </button>
const textureImage = './5.jpg'
const changeImage = () => {
    console.log('yyyy')
    textureImage.value = './6.jpg'
  }

**Comment by king2088** [comment]
就目前来说，并不支持动态改变textureImage，如果你想要动态改变textureImage，可能你需要修改源码`src/3dLoader/vue3dLoader.vue`文件，在watch中增加textureImage即可

**Comment by zhangxu1123** [comment]
改源码了自己发布一个npm包？

**Comment by king2088** [comment]
> 改源码了自己发布一个npm包？

如果只是应用于某一个项目，可以直接放在本地，不需要发布npm
