### ISSUE TITLE
请问一下作者，如何从服务端获取文件并且展示出来啊，比如stl文件存放在服务器上

### ISSUE THREAD

**Issue by FengIsTao** [king2088/vue-3d-loader#66]
请问一下作者，如何从服务端获取文件并且展示出来啊，比如stl文件存放在服务器上

**Comment by FengIsTao** [comment]
{
    "fileName": "2023-05-25/aLkKCEMsrWbJWRY.ply",
    "fileDownloadUri": "http://xxx.xxx.xxx.xxx:xxxxx/api/yt/oss/download_file/2023-05-25/aLkKCEMsrWbJWRY.ply",
    "fileType": "application/octet-stream",
    "size": 3577145,
    "fileStaticUri": "http://xxx.xxx.xxx.xxx:xxxxx/xxxxxxx/2023-05-25/aLkKCEMsrWbJWRY.ply"
}
1 就比如这是我上传的ply文件到服务器，然后服务器返回的内容如上，我要在页面展示出来，直接赋值地址好像没用。
2 我把fileDownloadUri赋值给dataset，然后好像没展示出来，所以问问您服务器地址如何展示？
 <vue3dLoader
        ref="vue3dLoaderRef"
        :webGLRendererOptions="webGLRendererOptions"
        :backgroundColor="backgroundColor"
        :backgroundAlpha="backgroundAlpha"
        :height="h"
        :width="w"
        :filePath="dataset"
        :autoPlay="autoPlay"
        :enableDamping="enableDamping"
        :outputEncoding="outputEncoding"
        :clearScene="clearScene"
        :dampingFactor="dampingFactor"
        :intersectRecursive="true"
        @process="onProcess"
        @load="onLoad"
        @click="onClick"
      />

**Comment by king2088** [comment]
只要你能够通过浏览器访问http://xxx.xxx.xxx.xxx:xxxxx/api/yt/oss/download_file/2023-05-25/aLkKCEMsrWbJWRY.ply并且下载文件，就说明这个地址是没有问题的，完全可以用于`filePath`，但是如果以上url无法通过浏览器访问并下载文件，则此url有问题无法使用。

**Comment by FengIsTao** [comment]
这样子啊，我试试，谢谢您

**Comment by king2088** [comment]
超过7天无回复及跟进
