### ISSUE TITLE
怎么设置模型自动绕其他轴旋转呢？

### ISSUE THREAD

**Issue by LYP857** [king2088/vue-3d-loader#68]
还有旋转一圈后停止，鼠标怎样才可以转动模型，demo中模型越变越小，而且停止了，鼠标也操作不了，

**Comment by king2088** [comment]
> 还有旋转一圈后停止，鼠标怎样才可以转动模型，demo中模型越变越小，而且停止了，鼠标也操作不了，

旋转的话，可以尝试通过动态改变摄像机位置来实现
