### ISSUE TITLE
请问资源路径问题

### ISSUE THREAD

**Issue by LYP857** [king2088/vue-3d-loader#69]
您好，我想请问一下，我的模型应该保存在哪例例呢，我试了一下保存在本地文件夹中，然后放路径url上去，访问不了啊.

![微信截图_20230605113756](https://github.com/king2088/vue-3d-loader/assets/100215619/e294a73d-be0b-4d03-894c-47c27886b1ce)

**Comment by king2088** [comment]
> 您好，我想请问一下，我的模型应该保存在哪例例呢，我试了一下保存在本地文件夹中，然后放路径url上去，访问不了啊.
> 
> ![微信截图_20230605113756](https://github.com/king2088/vue-3d-loader/assets/100215619/e294a73d-be0b-4d03-894c-47c27886b1ce)
> 
> 

资源路劲必须可以通过http协议访问，你这个本地文件肯定不行
