### ISSUE TITLE
当 mtlPath 为带签名的链接是，获取 loader 为空的问题

### ISSUE THREAD

**Issue by zhaojun1998** [king2088/vue-3d-loader#7]
查看代码发现是通过 `mtlPath` 的后缀来获取文件类型来加载 `loader` 的，但某些情况下，需要使用带鉴权的 `cdn` 或者其他类型的链接导致下载链接不包含后缀，就获取到空的 `loader` 了。

可否增加个手动指定 `loader` 的方法或者通过传入一个名字而不是根据 `mtlPath` 来获取 `loader`

**Comment by king2088** [comment]
> 

考虑过此问题，下个版本将实现此功能，thx！
