### ISSUE TITLE
为什么有些模型导入后没居中啊

### ISSUE THREAD

**Issue by FengIsTao** [king2088/vue-3d-loader#71]
![image](https://github.com/king2088/vue-3d-loader/assets/50825076/e85fb1c9-4cab-4781-b581-df3aca220b7c)

**Comment by king2088** [comment]
默认情况下不会重置或居中模型，会使用模型自己的位置信息

**Comment by king2088** [comment]
目前最新版已经支持显示xyz轴及显示网格，你可以使用开启并进行位置等调试。默认情况下如果不存在position、scale、rotation得值，将默认使用模型自己的值
