### ISSUE TITLE
请问支持修改obj文件局部的颜色和添加贴图么？

### ISSUE THREAD

**Issue by BeHappy0o0o0o0** [king2088/vue-3d-loader#72]
如题，请问支持修改obj文件局部的颜色和添加贴图么？

**Comment by king2088** [comment]
> 如题，请问支持修改obj文件局部的颜色和添加贴图么？

应该不可以

**Comment by BeHappy0o0o0o0** [comment]
好的，谢谢。

2023年7月24日 13:29，Tony ***@***.***> 写道：



如题，请问支持修改obj文件局部的颜色和添加贴图么？

应该不可以
