### ISSUE TITLE
如何设置有bin文件的gltf格式的模型

### ISSUE THREAD

**Issue by chen106186** [king2088/vue-3d-loader#73]
现在远程加载gltf格式的模型，除了有gltf文件还有一个匹配的bin文件，服务器部署完毕后无法拿到bin文件，这种情况，大佬该怎么解决？

**Comment by king2088** [comment]
> 现在远程加载gltf格式的模型，除了有gltf文件还有一个匹配的bin文件，服务器部署完毕后无法拿到bin文件，这种情况，大佬该怎么解决？

没有使用过gltf + bin文件的形式，目前也找不到相应的gltf+bin的3d文件进行测试，兴许，需要你自己进行查看是否是bin文件路径问题导致的找不到bin文件
