### ISSUE TITLE
vue版本冲突导致，引发onMounted等一系列生命周期问题

### ISSUE THREAD

**Issue by Zlinni** [king2088/vue-3d-loader#74]
由下面两图可以看见该项目锁定了指定的vue版本；如果开发的过程中引用该库的版本和实际的版本不一样则会导致项目报错
![image](https://github.com/king2088/vue-3d-loader/assets/78781776/b490ee20-2357-495b-a41d-3b0c90400a4d)
![image](https://github.com/king2088/vue-3d-loader/assets/78781776/52b38cf0-df4a-4cf5-b260-be7b161e3f12)
建议在rollup添加更改项：resolve: { dedupe: ['vue'] } 修改；或者vue改为devDependencies

**Comment by king2088** [comment]
> 由下面两图可以看见该项目锁定了指定的vue版本；如果开发的过程中引用该库的版本和实际的版本不一样则会导致项目报错 ![image](https://user-images.githubusercontent.com/78781776/257720687-b490ee20-2357-495b-a41d-3b0c90400a4d.png) ![image](https://user-images.githubusercontent.com/78781776/257720798-52b38cf0-df4a-4cf5-b260-be7b161e3f12.png) 建议在rollup添加更改项：resolve: { dedupe: ['vue'] } 修改；或者vue改为devDependencies

如果你使用的是vue2，请安装1.x.x版本。如果是vue3则直接使用2.x.x，是不是你使用vue2开发，引入了2.x.x版本导致报错生命周期？

**Comment by Zlinni** [comment]
> > 通过两张图可以看到该项目锁定了指定的vue版本；如果开发的过程中该引用库的版本和实际的版本不一样导致下面项目报错建议在rollup添加更改项：resolve: { dedupe: [ ' vue'] } 修改；或者vue改为devDependencies![图像](https://user-images.githubusercontent.com/78781776/257720687-b490ee20-2357-495b-a41d-3b0c90400a4d.png) ![图像](https://user-images.githubusercontent.com/78781776/257720798-52b38cf0-df4a-4cf5-b260-be7b161e3f12.png)
> 
> 如果你使用的是vue2，请安装1.xx版本。如果是vue3则直接使用2.xx，是不是你使用vue2开发，引入了2.xx版本导致报错生命周期？

我使用的是^3.2.13的vue版本
