### ISSUE TITLE
当我拖动模型时，一下显示一下隐藏，控制台显示这个警告，这是什么原因呀

### ISSUE THREAD

**Issue by FengIsTao** [king2088/vue-3d-loader#75]
![image](https://github.com/king2088/vue-3d-loader/assets/50825076/8f7470b9-ad9a-4611-81d7-54a6ec60196c)

**Comment by king2088** [comment]
应该是多次调用组件渲染导致的，比如组件某个属性一直再改变导致的

**Comment by FengIsTao** [comment]
好像是这个原因，就是集成到大屏里，然后我拖动，然后看到控制台报警告，但是是能显示出来的，就是拖的时候不显示，然后结束拖动就显示了，就很奇怪，所以问问您

**Comment by king2088** [comment]
> 好像是这个原因，就是集成到大屏里，然后我拖动，然后看到控制台报警告，但是是能显示出来的，就是拖的时候不显示，然后结束拖动就显示了，就很奇怪，所以问问您

你需要检查一下，传入vue-3d-loader的各个参数，在拖动的时候是否都发生了变化，如果发生了变化就会导致vue-3d-loader进行重绘

**Comment by FengIsTao** [comment]
这样啊，谢谢作者大大，嗯
