### ISSUE TITLE
模型加载后位置大小问题

### ISSUE THREAD

**Issue by LYP857** [king2088/vue-3d-loader#77]
有些模型加载完后特别大，有些又很小，怎么样才可以设置模型加载完后居中，并且自适应大小呢
这是直接加载模型的图片
![image](https://github.com/king2088/vue-3d-loader/assets/100215619/79396bcf-8024-4ebd-a637-fa7920cb6148)
下面是网站浏览模型的
![image](https://github.com/king2088/vue-3d-loader/assets/100215619/86d8be81-5a6a-4040-8b85-820a488c3196)
qiu求大佬指教

**Comment by king2088** [comment]
关于模型大小问题，默认情况下是根据模型自己设置的大小、位置进行设置的。只有用户设定后才会发生变化。

**Comment by lin-credible** [comment]
所以目前是没法根据画布大小自适应调整模型本身的大小和位置是么？
