### ISSUE TITLE
设置容器样式问题

### ISSUE THREAD

**Issue by LYP857** [king2088/vue-3d-loader#78]
为什么这样配置，值会显示一点点模型，结果如下图
![image](https://github.com/king2088/vue-3d-loader/assets/100215619/8dae275e-9846-40ae-9723-d20aeda8fee7)
![image](https://github.com/king2088/vue-3d-loader/assets/100215619/f450dd8c-b810-432a-baee-3e804ce4097b)
结果：
![没有配置canvas](https://github.com/king2088/vue-3d-loader/assets/100215619/d314532e-70ab-4655-b15c-0278ca9e4e13)
配置canvas后才可以显示
![canvas配置](https://github.com/king2088/vue-3d-loader/assets/100215619/b1a74b87-df1e-4751-b8a3-865ed98fd814)
配置完的结果：
![配置canvas后](https://github.com/king2088/vue-3d-loader/assets/100215619/292fe40d-1e88-4e6f-900c-855fa877f38a)
不太熟悉vue3，望大神赐教

**Comment by king2088** [comment]
默认情况下画布宽高是根据其父元素宽高的100%自动设置的，如果父元素没有设置宽高，就会出现看不到模型的情况。
