### ISSUE TITLE
有办法提供坐标和网格线吗？

### ISSUE THREAD

**Issue by Zlinni** [king2088/vue-3d-loader#80]
这个功能对于调试初始模型位置和旋转比较常用，希望能够加上！

**Comment by king2088** [comment]
> 这个功能对于调试初始模型位置和旋转比较常用，希望能够加上！

先加入下一版本计划，待后续再增加此功能

**Comment by king2088** [comment]
最新版2.1.8中提供了坐标和网格线，请查看redme.md文档中的API，`enableAxesHelper`与`enableGridHelper`
