### ISSUE TITLE
 你能支持在加载时获取对象大小吗？

### ISSUE THREAD

**Issue by kamitori** [king2088/vue-3d-loader#81]
你能支持在像这样加载时获取对象大小吗? 如果没有，也没关系。先感谢您
https://discourse.threejs.org/t/find-the-size-of-a-loaded-gltf-model/38515

**Comment by king2088** [comment]
> 你能支持在像这样加载时获取对象大小吗? 如果没有，也没关系。先感谢您 https://discourse.threejs.org/t/find-the-size-of-a-loaded-gltf-model/38515

你好，根据插件的用途（用于多种3D模型展示），暂时不考虑开发获取对象大小的功能。不过目前`load`事件将整个画布上的对象都返回了，兴许，你可以通过load事件来获取到对象。源码：https://github.com/king2088/vue-3d-loader/blob/master/src/3dLoader/vue3dLoader.vue#L697C29-L697C29，不过由于目前并未将three对象导出，可能你需要自己引入threeJS进行获取size，下一版本将支持导出threeJS

**Comment by king2088** [comment]
```js
import { vue3dLoader, Three } from 'vue-3d-loader'
load(obj) {
    var box = new Three.Box3().setFromObject( obj[0] );
    var size = box.getSize();
     console.log( size );
}
```

**Comment by sweetlicio** [comment]
你好。请问下。如何通过type判定改变某一个模型的颜色。比如说有没有类似getobjectbyname().这样的方法。
