### ISSUE TITLE
在大屏中引用组件。加载模型之后。如果是大屏中的数据变化。模型就是闪烁。

### ISSUE THREAD

**Issue by sweetlicio** [king2088/vue-3d-loader#82]
您好。在vue2做大屏时，使用vue3dloader加载多模型。模型作为底图，展示数据的变化。我这边遇到一个问题。1.点击选中模型，改变大屏数据，模型就会闪烁或者位置发生位移。有遇到过吗。十分感谢。vue3dloader是很棒的工具。

**Comment by king2088** [comment]
> 您好。在vue2做大屏时，使用vue3dloader加载多模型。模型作为底图，展示数据的变化。我这边遇到一个问题。1.点击选中模型，改变大屏数据，模型就会闪烁或者位置发生位移。有遇到过吗。十分感谢。vue3dloader是很棒的工具。

能否提供一些主要的代码？
