### ISSUE TITLE
支持网格、坐标轴的打开关闭事件操作

### ISSUE THREAD

**Issue by HalfLeaf** [king2088/vue-3d-loader#83]
目前已支持网格、坐标轴，请问如何在不重载模型的情况下，由用户操作，网格和坐标轴是否打开呢？
或者能提供重新载入模型的方法

**Comment by king2088** [comment]
> 目前已支持网格、坐标轴，请问如何在不重载模型的情况下，由用户操作，网格和坐标轴是否打开呢？
> 或者能提供重新载入模型的方法

未对坐标轴及网格做watch，因此无法实时设置开启/关闭。如果有此需求，下一版本中加入watch

**Comment by HalfLeaf** [comment]
ths
