### ISSUE TITLE
安装好运行时报错 You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by TAKeke** [king2088/vue-3d-loader#84]
版本1.2.18，使用的vue2
Module parse failed: Unexpected token (33250:5)
You may need an appropriate loader to handle this file type.
|                       var Sw = {
|                                       install: Mw,
|                                       ...ww
|                               },
|                               Tw = Sw

**Comment by king2088** [comment]
提供的信息不详细，无法得知你本地环境。
经过我本地测试，并未发现如此错误。本地测试使用的vue2版本为2.6.14，vue-3d-loader版本为1.2.18，run以及build都未出现问题。
鉴于你的错误，给出以下处理方法：
- 请删除node_modules文件夹
- 重新npm install或yarn
- 升级vue2版本

**Comment by TAKeke** [comment]
const ww = [bw]
var Sw = {
install: Mw,
//  ...ww
},
将...ww注释后，可以正常运行，ww类型为数组

**Comment by TAKeke** [comment]
> 提供的信息不详细，无法得知你本地环境。 经过我本地测试，并未发现如此错误。本地测试使用的vue2版本为2.6.14，vue-3d-loader版本为1.2.18，run以及build都未出现问题。 鉴于你的错误，给出以下处理方法：
> 
> * 请删除node_modules文件夹
> * 重新npm install或yarn
> * 升级vue2版本

我将...ww注释后，可以正常运行，好像是类型出了问题，ww类型为数组

**Comment by king2088** [comment]
> > 提供的信息不详细，无法得知你本地环境。 经过我本地测试，并未发现如此错误。本地测试使用的vue2版本为2.6.14，vue-3d-loader版本为1.2.18，run以及build都未出现问题。 鉴于你的错误，给出以下处理方法：
> > 
> > * 请删除node_modules文件夹
> > * 重新npm install或yarn
> > * 升级vue2版本
> 
> 我将...ww注释后，可以正常运行，好像是类型出了问题，ww类型为数组

那是因为vue-3d-loader导致的还是你自己代码导致的？

**Comment by TAKeke** [comment]
> > > 提供的信息不详细，无法得知你本地环境。 经过我本地测试，并未发现如此错误。本地测试使用的vue2版本为2.6.14，vue-3d-loader版本为1.2.18，run以及build都未出现问题。 鉴于你的错误，给出以下处理方法：
> > > 
> > > * 请删除node_modules文件夹
> > > * 重新npm install或yarn
> > > * 升级vue2版本
> > 
> > 
> > 我将...ww注释后，可以正常运行，好像是类型出了问题，ww类型为数组
> 
> 那是因为vue-3d-loader导致的还是你自己代码导致的？

我更改的是_vue-3d-loader@1.2.18@vue-3d-loader/dist/vue-3d-loader.umd.min.js 里的代码，我看了未压缩的代码应该是

**Comment by king2088** [comment]
你用的到底是vue2的什么版本？

**Comment by TAKeke** [comment]
> 你用的到底是vue2的什么版本？

2.7.14

**Comment by king2088** [comment]
我也使用了vue@2.7.14，并未出现你说的错误，而你说的components是一个数组不能往对象中赋值，我并未将数组赋值到对象，而是将数组扁平化后再赋的值
