### ISSUE TITLE
【求助】模型点击事件

### ISSUE THREAD

**Issue by JaneYork** [king2088/vue-3d-loader#89]
比如：有4个仓库，点击每个仓库出现弹窗然后请求接口仓库数据怎么实现呢？  模型是一整个然后怎么标点呢？ 还是模型是多个小的？

**Comment by king2088** [comment]
> 比如：有4个仓库，点击每个仓库出现弹窗然后请求接口仓库数据怎么实现呢？ 模型是一整个然后怎么标点呢？ 还是模型是多个小的？

可以利用`onMouseDown`事件(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/events.html`，`https://king2088.github.io/vue-3d-loader-docs/zh/guide/event.html`)，并结合`intersectRecursive`(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#intersectrecursive`)深层获取模型，即可！
在深层获取模型的过程中，可以获取到模型中的子项。除非此模型就只有单独的一个线条，你可以自行尝试一下。

**Comment by king2088** [comment]
> 比如：有4个仓库，点击每个仓库出现弹窗然后请求接口仓库数据怎么实现呢？ 模型是一整个然后怎么标点呢？ 还是模型是多个小的？

可以利用`onMouseDown`事件(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/events.html`，`https://king2088.github.io/vue-3d-loader-docs/zh/guide/event.html`)，并结合`intersectRecursive`(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#intersectrecursive`)深层获取模型，即可！
在深层获取模型的过程中，可以获取到模型中的子项。除非此模型就只有单独的一个线条，你可以自行尝试一下。

**Comment by JaneYork** [comment]
> > 比如：有4个仓库，点击每个仓库出现弹窗然后请求接口仓库数据怎么实现呢？ 模型是一整个然后怎么标点呢？ 还是模型是多个小的？
> 
> 可以利用`onMouseDown`事件(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/events.html`，`https://king2088.github.io/vue-3d-loader-docs/zh/guide/event.html`)，并结合`intersectRecursive`(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#intersectrecursive`)深层获取模型，即可！ 在深层获取模型的过程中，可以获取到模型中的子项。除非此模型就只有单独的一个线条，你可以自行尝试一下。

@king2088    对模型有啥要求吗？  是不是可以这么理解，在建模型的时候，就得把模型弄成好几个子项子模块？  而不是一坨整个的模型？

**Comment by king2088** [comment]
> > > 比如：有4个仓库，点击每个仓库出现弹窗然后请求接口仓库数据怎么实现呢？ 模型是一整个然后怎么标点呢？ 还是模型是多个小的？
> > 
> > 可以利用`onMouseDown`事件(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/events.html`，`https://king2088.github.io/vue-3d-loader-docs/zh/guide/event.html`)，并结合`intersectRecursive`(`https://king2088.github.io/vue-3d-loader-docs/zh/guide/api.html#intersectrecursive`)深层获取模型，即可！ 在深层获取模型的过程中，可以获取到模型中的子项。除非此模型就只有单独的一个线条，你可以自行尝试一下。
> 
> @king2088    对模型有啥要求吗？  是不是可以这么理解，在建模型的时候，就得把模型弄成好几个子项子模块？  而不是一坨整个的模型？

我不是专业的建模人员，这一块我不是很清楚，但是模型有分类肯定是更好的。不过根据我的经验，模型都是由点、线、三角形、面等组成，理论上来说是可以深层选择到对应的内容上的。应该不需要将一个模型拆分为两个模型或者多个模型
