### ISSUE TITLE
请问下模型怎么控制缩放程度呢，现在是没有限制，然后阔以缩放到很小。

### ISSUE THREAD

**Issue by huanjielin** [king2088/vue-3d-loader#9]

**Comment by king2088** [comment]
缩放是用户通过鼠标滚轮自行进行的事件，目前并未对缩放大小比例做任何限制。如果你想禁用缩放功能，可以参考https://github.com/king2088/vue-3d-loader/blob/master/src/examples/interactive-controls.vue

**Comment by huanjielin** [comment]
目前是没有要禁用，是想控制缩放的大小比例，目前是否还没开启入口配置项需要从源码入手呢。

**Comment by king2088** [comment]
> 

目前并没有这样的配置及入口，如需控制比例，请修改源码，可以通过监听鼠标滚轮事件mousewheel，通过返回camera或wrapper得到相对应的缩放比例，进行控制

**Comment by huanjielin** [comment]
好的 谢谢。
