### ISSUE TITLE
在html中引入vue进行代码书写后，无法使用vue-3d-loader

### ISSUE THREAD

**Issue by TECNB** [king2088/vue-3d-loader#91]
html页面使用vue-3d-loader时

如果采用符合vue2的1.3.0的版本，那么就会直接无法找到vue-3d-loader，
报错：
Uncaught SyntaxError: The requested module '../../plugins/node_modules/vue-3d-loader/dist/vue-3d-loader.umd.min.js' does not provide an export named 'default' (at list.html:167:14)

如果采用不符合vue2的2.2.0的版本，那么这样就可以找到vue-3d-loader，上面的报错消失，但是出现新的报错，这次是直接找不到vue

报错：

Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

部分代码如下：
![截屏2023-10-23 21.50.46](https://picdl.sunbangyan.cn/2023/10/23/9ad0e5997447b9523a161ce47e8f8786.png)

**Comment by king2088** [comment]
请设置版本号后再试，如：https://[unpkg.com/vue-3d-loader@1.3.0/dist/vue-3d-loader.umd.min.js](https://unpkg.com/vue-3d-loader@1.3.0/dist/vue-3d-loader.umd.min.js)

**Comment by TECNB** [comment]
版本号修改后报错如下，不知道怎么解决：
Uncaught SyntaxError: The requested module 'https://unpkg.com/vue-3d-loader@1.3.0/dist/vue-3d-loader.umd.min.js' does not provide an export named 'vue3dLoader' (at list.html:167:15)

**Comment by king2088** [comment]
看似并不支持再html中引入

**Comment by TECNB** [comment]
另外我很想知道是怎么实现多个texture渲染同一个模型的,我自己采用three.js就只能采用子节点的方法，但是有时候模型就只有一个节点，但是下载下来的模型截图却有很多张
![截屏2023-10-23 21.50.46](https://picdl.sunbangyan.cn/2023/10/23/9fe14313dd1c757f140922a97bcbea9f.png)

**Comment by king2088** [comment]
> 另外我很想知道是怎么实现多个texture渲染同一个模型的,我自己采用three.js就只能采用子节点的方法，但是有时候模型就只有一个节点，但是下载下来的模型材质图却有很多张 ![截屏2023-10-23 21.50.46](https://camo.githubusercontent.com/16e3e4d539d50f1863d8aa543ec2886c6ba973b3f921231bbb657bb0738181d3/68747470733a2f2f706963646c2e73756e62616e6779616e2e636e2f323032332f31302f32332f39666531343331336464316337353766313430393232613937626362656139662e706e67)

此问题我并未深究过，可能需要你去threeJS官方查看相关实例或文档

**Comment by TECNB** [comment]
那组件中的textureImage是怎么实现渲染的呢
![截屏2023-10-23 21.50.46](https://picdl.sunbangyan.cn/2023/10/23/389ad36e11c233a03f202c4e7e9d7b41.png)

**Comment by king2088** [comment]
![image](https://github.com/king2088/vue-3d-loader/assets/20067250/383ea540-9297-4095-b509-82104025b3c5)
采用TextureLoader实现的，官方文档：https://threejs.org/docs/index.html?q=text#api/en/loaders/TextureLoader
