### ISSUE TITLE
大牛，请问如何绑定光源？现有api支持吗

### ISSUE THREAD

**Issue by ZhiLunXu** [king2088/vue-3d-loader#98]

**Comment by king2088** [comment]
关于灯光，请查阅文档：https://king2088.github.io/vue-3d-loader-docs/zh/guide/example/lights.html

**Comment by ZhiLunXu** [comment]
这个不会跟谁我旋转是光源移动

**Comment by king2088** [comment]
需要对点光源进行位置跟随camera，我把你提的问题加入需求，下一个版本出这个功能！大概明天你就可以使用了
